### ISSUE TITLE
GeolocationStatus.disabled isn't returned if Location is turned off

### ISSUE THREAD

**Issue by escamoteur** [BaseflowIT/flutter-geolocator#108]
Hi,

while testing I found that if the location service is disabled a call to geCurrentLocation just won't return until the service is switched on. 

Calling checkGeolocationPermissionStatus doesn't help either because it will just return granted if the permissions are right and seems not to check id the service is available.

Cheers
Thomas

**Comment by mvanbeusekom** [comment]
#109

**Comment by mvanbeusekom** [comment]
#109

**Comment by mvanbeusekom** [comment]
@escamoteur we just release version 2.1.0 which implemented this feature. Let us know what you think.

**Comment by jfdeveloper92** [comment]
in 5.1.3 status is returning granted even when the location services are off.

this is my code. Maybe im doing something wrong?

GeolocationStatus geolocationStatus  = await Geolocator().checkGeolocationPermissionStatus();
        print(geolocationStatus.toString());


        if(geolocationStatus == GeolocationStatus.disabled){
          _showLocationMessage(message: "Please turn on location services", callback: (){
            Navigator.pop(context);
          });
          return;
        }
------------------------------------
I am using a pixel 1 on 9.0 
print(geolocationStatus.toString()); returns GeolocationStatus.granted when location is off.

**Comment by mvanbeusekom** [comment]
Yes that is perfectly legal. The availability of the location service and the fact that permissions are granted are two separate entities.

You can still request permissions to access location information if the user has turned off the location services. You can use the `isLocationServiceEnabled` method to check if the location services are enabled or not and if necessary ask the user to turn them on if this is required for your App.

**Comment by jfdeveloper92** [comment]
Thank you. That worked as expected.

**Comment by ScholliYT** [comment]
Maybe this should be added to the main documentation. I find "to check if location services are enabled you can call the checkGeolocationPermissionStatus method" is very confusing related to this.
