### ISSUE TITLE
Please include the function to check if the location service is on or off on the device

### ISSUE THREAD

**Issue by hafizidev** [BaseflowIT/flutter-geolocator#109]
## 🚀 Feature Requests

Please add a function to check if location service is on or off on device.

### Describe the feature
Android : 
```
public static boolean isLocationEnabled(Context context) {
    int locationMode = 0;
    String locationProviders;
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT){
        try {
            locationMode = Settings.Secure.getInt(context.getContentResolver(), Settings.Secure.LOCATION_MODE);
        } catch (SettingNotFoundException e) {
            e.printStackTrace();
            return false;
        }
        return locationMode != Settings.Secure.LOCATION_MODE_OFF;
    }else{
        locationProviders = Settings.Secure.getString(context.getContentResolver(), Settings.Secure.LOCATION_PROVIDERS_ALLOWED);
        return !TextUtils.isEmpty(locationProviders);
    }
} 
```
Refference : https://stackoverflow.com/a/22980843

iOS:
```

```

### Platforms affected (mark all that apply)
- [&#10006;] :iphone: iOS
- [&#10004;] :robot: Android

**Comment by OZ20** [comment]
Yup, i was confused at first when i read the readme file that says it has feature to check if the service are disabled or enabled.

**Comment by mvanbeusekom** [comment]
https://github.com/BaseflowIT/flutter-permission-handler/pull/32

**Comment by mvanbeusekom** [comment]
@hafizidev, @OZ20, we just release version 2.1.0 which implemented this feature. Let us know what you think.

**Comment by dark-chocolate** [comment]
@mvanbeusekom  Is there any way to open the location settings page in iOS too? For android, I am using Intents and it is working fine for me.

**Comment by Ahmed-Husnein-Choudhury** [comment]
Use app_settings plugin to access device settings.
