### ISSUE TITLE
error: Target of URI doesn't exist: 'package:geolocation/geolocation.dart

### ISSUE THREAD

**Issue by alexlovar** [BaseflowIT/flutter-geolocator#111]
hi, i'm using this plugin but afther add the dependence in pubspec.yaml
geolocator: "^1.7.0"
i'm importing into a dart file ->
 import 'package:geolocation/geolocation.dart';
i did flutter packages get, but in my dart analysis i get.
error: Target of URI doesn't exist: 'package:geolocation/geolocation.dart'. (uri_does_not_exist at [xxxxx] lib\screens\Home\tab_location.dart:8)

>
 flutter doctor -v
[√] Flutter (Channel dev, v0.8.4, on Microsoft Windows [VersiÃ³n 10.0.14393], locale es-US)
    • Flutter version 0.8.4 at c:\flutter
    • Framework revision 7f7a731da0 (2 days ago), 2018-09-14 13:11:32 -0400
    • Engine revision 7a9b430d74
    • Dart version 2.1.0-dev.4.0.flutter-c28db2d6e1

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Alex\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    X Android license status unknown.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.

> 
how i do to solve this  error?

thank you

**Comment by mvanbeusekom** [comment]
@alexlovar you have a typing error in your import. You have:
```
import 'package:geolocation/geolocation.dart';
```

It should be:
```
import 'package:geolocator/geolocator.dart';
```

**Comment by alexlovar** [comment]
thank you so much!
