### ISSUE TITLE
README.md cleanup

### ISSUE THREAD

**Issue by ishaanbahal** [BaseflowIT/flutter-geolocator#114]
### Pitch
I have found a couple of issues in the documentation/README.md, not quite sure if I'm right, hence creating an issue and not a PR.

#### Issues:
- https://github.com/baseflowit/flutter-geolocator#geolocation 
```
import 'package:geolocator/geolocator.dart';

Position position = await Geolocator().getCurrentPosition(desiredAccuracy: LocationAccuracy.high);
```
desiredAccuracy seems to be a positional argument and not a named argument. The line should be:
```
Position position = await Geolocator().getCurrentPosition(LocationAccuracy.high);
```

- https://github.com/baseflowit/flutter-geolocator#geocoding
```
import 'package:geolocator/geolocator.dart';

Placemark placemark = await Geolocator().placemarkFromAddress("Gronausestraat 710, Enschede");
```
Here `placemarkFromAddress()` returns a List<Placemark> and not a `Placemark`. Should be:
```
List<Placemark> placemark = await Geolocator().placemarkFromAddress("Gronausestraat 710, Enschede");
```

There can be a few more issues, but I didn't need more info than this, so I didn't try. 

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
@ishaanbahal thank you very much for your feedback. 

We have just released version 2.0.0 of the Plugin and with this version we also updated the arguments to be named arguments instead of positional arguments (which fixes that part of the README ;) ).

And indeed the `placemarkFromAddress` and `placemarkFromCoordinates` do return a list, I will definitely correct this in de readme.

**Comment by ishaanbahal** [comment]
You might want to mention its a breaking change, since people coming from 1.7.0 would have to move from using positional arguments to named arguments. Anyway, thanks a lot for the update, and the plugin! :)

**Comment by mvanbeusekom** [comment]
@ishaanbahal I was almost sure I did, but you are 100% right. A PR to update the changelog (#116 ) is submitted for review.

Thanks for your feedback!

**Comment by ishaanbahal** [comment]
Awesome! 👍
