### ISSUE TITLE
Doesn't build without !use_framework

### ISSUE THREAD

**Issue by d1xlord** [BaseflowIT/flutter-geolocator#120]
## 🐛 Bug Report

Cannot build the app for iOS with the '!use_framework' commented out. This causes an issue when using with other libraries (map_view, firebase_*)

### Expected behavior
This should be build as to not require the '!use_framework' option on podfile.

### Reproduction steps
Try building with 'map_view' and 'geolocator' both present in the pubspec.yaml

### Configuration

**Version:** 1.x

**Platform:** 
- [*] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
@d1xlord have you already looked at issue #17? Here we discuss similar problem which is solved by adding the correct "SWIFT_VERSION" to the build settings in the Podfile. 

Unfortunately due to a bug in Flutter we need to include the `use_framework!` option to be able to support development using Swift (see [Flutter#16049](https://github.com/flutter/flutter/issues/16049) , this is also mentioned in out README.md).

**Comment by d1xlord** [comment]
I have already looked into the issue #17 but found no solution as I cannot put use_framework inside the podfile as it causes issue with other libraries I need.

I already have the SWIFT_VERSION inside the post_install block but that doesn't help either. I get an error with
`'google_api_availability/google_api_availability-Swift.h' file not found`

**Comment by mvanbeusekom** [comment]
@d1xlord, I have looked into this a little bit and found two ways to possibly solve the problem:

1. We convert this project to Objective-c (which we don't have the time for, so if someone else is willing to do so PR's are welcome);
2. From my understanding on this GitHub issue [Flutter#14161](https://github.com/flutter/flutter/issues/14161), your issue could be solved if the guys at `map_view` add the line `s.static_framework = true` to their [map_view.podspec](https://github.com/apptreesoftware/flutter_google_map_view/blob/master/ios/map_view.podspec) file (you should be able to give this a try by cloning their repo, updating the .podspec file and referencing the plugin locally).

Of course we are open for other solutions.
