### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by ovvenkatesan** [BaseflowIT/flutter-geolocator#132]
* What went wrong:
A problem occurred configuring project ':google_api_availability'.
> Failed to notify project evaluation listener.
   > java.lang.AbstractMethodError (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
  Command: /Users/venkat/flutterProjects/farm_mojo/android/gradlew app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.

**Comment by mvanbeusekom** [comment]
Hi @ovvenkatesan, this problem happens because of a mismatch of Gradle versions used. Solutions to this problem are discussed in issues #127 and #130
