### ISSUE TITLE
Build fails with Firebase Auth and Firestore

### ISSUE THREAD

**Issue by echosalik** [BaseflowIT/flutter-geolocator#133]
## 💬 Questions and Help
Hi
I am trying to build an app but I get the following error, using the latest plugin version:

```
Launching lib/main.dart on Redmi 4A in debug mode...
Initializing gradle...
Resolving dependencies...
[{"event":"app.progress","params":{"appId":"1ff9befd-d704-4c12-a7cc-4e35d787ddd8","id":"2","progressId":null,"message":"Gradle task 'assembleDebug'..."}}]Gradle task 'assembleDebug'...

registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 34s
Finished with error: Gradle task assembleDebug failed with exit code 1
```
I have a feeling this is related to Google Services Version. But I dont know which version are used where. A little help please.

Regards
PS: Multidex is enabled

VERSIONS:
```
$ flutter doctor -v
[✓] Flutter (Channel dev, v0.10.1, on Mac OS X 10.13.6 17G65, locale en-PK)
    • Flutter version 0.10.1 at /Users/echosalik/flutter
    • Framework revision 6a3ff018b1 (10 days ago), 2018-10-18 18:38:26 -0400
    • Engine revision 3860a43379
    • Dart version 2.1.0-dev.7.1.flutter-b99bcfd309

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/echosalik/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-P, build-tools 27.0.3
    • ANDROID_HOME = /Users/echosalik/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/XCODE9.4/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected device (1 available)
    • Redmi 4A • 2a26f2627d93 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by mvanbeusekom** [comment]
@echosalik can you please check which version of Gradle you are using? 

Have a look at #130 and #127. I might be possible your gradle version is outdated and causing these problems.

**Comment by echosalik** [comment]
Thanks for your prompt reply. I am testing your suggestion, gradle-wrapper.properties file is the one where I'll update the version, right?

**Comment by mvanbeusekom** [comment]
@echosalik, the `gradle-wrapper.properties` is one of the locations indeed. So what you'll need to do is:

1. Update the `distributionUrl` in all of the `gradle-wrapper.properties` file (this should be `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip`)
2. Make sure the `classpath` for the `com.android.tools.build:gradle` in all of the `build.gradle` files is up to date (this should be: `classpath 'com.android.tools.build:gradle:3.2.1'`)

The reason I mention "all of the ... files" is that depending on you project configuration there can be multiple.

**Comment by echosalik** [comment]
Great. Thanks man! Trying it out.

Regards

**Comment by mvanbeusekom** [comment]
Let us know how it works out.

**Comment by echosalik** [comment]
BTW i just searched for the error again and got this [issue](https://github.com/flutter/flutter/issues/22173) in flutter for **geolocator**

**Comment by echosalik** [comment]
Sure. Thanks 👍

**Comment by OZ20** [comment]
> @mvanbeusekom Unfortunately, I am having the exact same error. I only have one `gradle-wrapper.properties` and changed the classpath version to `3.2.1`.
> I had to apply [this](https://github.com/flutter/flutter/commit/e93d19c0e7805e375b650ddf69009fa4549ad678#diff-d9b052388990c36138e397b5bb529025) fix to flutter though. But I still have the same error.

3.2.1 is bugged when using this plugin , try downgrade to 3.1.2 while using gradle wrapper above version 4.4

**Comment by echosalik** [comment]
@OZ20 unfortunately no. I am using another plugin now.
But I would love to use this plugin for next update. Other plugin lacks some features.

**Comment by kidnapkin** [comment]
https://github.com/flutter/flutter/issues/23131#issuecomment-430523619
Helped me

**Comment by mwanders98** [comment]
I had the same Issue. 

I could resolve it through adding following to _android/app/build.gradle_:

```
defaultConfig {
    ...
    multiDexEnabled true
}
```
In addition to that I followed @kidnapkin 's recommendation.

> [flutter/flutter#23131 (comment)](https://github.com/flutter/flutter/issues/23131#issuecomment-430523619)
> Helped me

**Comment by echosalik** [comment]
> 
> 
> I had the same Issue.
> 
> I could resolve it through adding following to _android/app/build.gradle_:
> 
> ```
> defaultConfig {
>     ...
>     multiDexEnabled true
> }
> ```
> 
> In addition to that I followed @kidnapkin 's recommendation.
> 
> > [flutter/flutter#23131 (comment)](https://github.com/flutter/flutter/issues/23131#issuecomment-430523619)
> > Helped me

I already had multidex, firestore needs multidex, so sorry that didn't work.

I have yet to try if there are any new updates though.

**Comment by YogeshLegendkiller** [comment]
facing same issue any update

**Comment by RicardoRB** [comment]
Same problem here

**Comment by mvanbeusekom** [comment]
Version 5.0.0 is completely refactored to use Objective-C instead of utilizing Swift. This should prevent these problems.

**Comment by egyleader** [comment]
Hi everyone .. there is a better solution than enable multidex ,,, please see this answer :

https://github.com/flutter/flutter/issues/20747#issuecomment-614676669
