### ISSUE TITLE
Comments in the example code

### ISSUE THREAD

**Issue by vinicentus** [BaseflowIT/flutter-geolocator#136]
## 🏗 Enhancement Proposal

It would be nice to have comments in the example code, explaining how the examples work.

### Pitch

This should make understanding how to use this plugin a bit easier.

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by StijnWoerkom** [comment]
@vinicentus There are comments in the example code explaining what the code does. Is it easier to understand or do you have any suggestions for improving the example code?
