### ISSUE TITLE
Prompt user to enable location service

### ISSUE THREAD

**Issue by naumanahmed19** [BaseflowIT/flutter-geolocator#138]
Anyway to prompt user to enable GPS like this screenshot.

<img src="https://i.stack.imgur.com/u9Q4D.png">

**Comment by NightkingCH** [comment]
I didn't find a way to do this natively and ended up to implement it by my own. I used the following plugin [https://pub.dartlang.org/packages/simple_permissions](url) check the permission as well. In combination with those two plugins I got a nice expirience which I can exchange later when there is some better solution :). The good thing is, this will work on iOS and Android. The plugin supports iOS as well 👍 .



        GeolocationStatus status = await Geolocator().checkGeolocationPermissionStatus();
        if (status == GeolocationStatus.disabled) {
          showDialog(
            context: context,
            builder: (_) {
              return new AlertDialog(
                content: Text(
                  "To continue, let your device turn on location using Google's location service.",
                  style: new TextStyle(color: Colors.black54),
                ),
                actions: <Widget>[
                  FlatButton(
                    child: Text('CANCEL'),
                    onPressed: () async {
                      Navigator.of(context).pop();
                    },
                  ),
                  FlatButton(
                    child: Text('OK'),
                    onPressed: () async {
                      await SimplePermissions.openSettings();
                      Navigator.of(context).pop();
                    },
                  ),
                ],
              );
            },
          );
          return;
        }

        if (status != GeolocationStatus.granted) {
          PermissionStatus permStatus = await SimplePermissions.requestPermission(Permission.AccessFineLocation);

          if(permStatus != PermissionStatus.authorized) {
            return;
          }
        }
        // do some fancy geo stuff
        Position position = await Geolocator().getCurrentPosition(desiredAccuracy: LocationAccuracy.high);

**Comment by mvanbeusekom** [comment]
@naumanahmed19, the `Geolocator` plugin used the `permission_handler` plugin to initially handle permissions. You can also directly use the `permission_handler` plugin directly if you need more fine grained control on requesting permissions.

You can use the `shouldShowRequestPermissionRationale` to show a default notification message as shown in your screenshot. Or you could for example use the `checkPermissionStatus` method to get informed about the current permission status and show a custom dialog window (similar to what @NightkingCH is doing in his example). The `permission_handler` is also available for both iOS and Android and supports a wide range of permissions (a more that the `simple_permissions` plugin mentioned by @NightkingCH.

More information about the permission_handler plugin can be found here:
- Project site: https://github.com/baseflowit/flutter-permission-handler
- Pub: https://pub.dartlang.org/packages/permission_handler
