### ISSUE TITLE
placemarkFromCoordinates results different on IOS  and Android

### ISSUE THREAD

**Issue by naumanahmed19** [BaseflowIT/flutter-geolocator#140]
placemarkFromCoordinates returning different results on IOS and android is this a bug or I am missing something? At android its working fine but on IOS few attributes like (thoroughfare, locality) are missing.

```
 List<Placemark> placemark =
            await Geolocator().placemarkFromCoordinates(52.2165157, 6.9437819);
        print("name: " + placemark.first.name);
        print("country: " + placemark.first.country);
        print("administrativeArea: " + placemark.first.administrativeArea);
        print("subAdministratieArea: " + placemark.first.subAdministratieArea);
        print("locality: " + placemark.first.locality);
        print("subLocality: " + placemark.first.subLocality);
        print("thoroughfare: " + placemark.first.thoroughfare);
        print("subThoroughfare: " + placemark.first.subThoroughfare);
```

Android Results:
```
I/flutter (25085): name: 24
I/flutter (25085): country: Netherlands
I/flutter (25085): administrativeArea: Overijssel
I/flutter (25085): subAdministratieArea: Enschede
I/flutter (25085): locality: Enschede
I/flutter (25085): subLocality: Eschmarke
I/flutter (25085): thoroughfare: Waterlelielaan
I/flutter (25085): subThoroughfare: 24
```

IOS Results:

```
flutter: name: Waterlelielaan 24             //different
flutter: country: Netherlands
flutter: administrativeArea: Overijssel
flutter: subAdministratieArea: Enschede
flutter: locality: Enschede
flutter: subLocality:                                //missing
flutter: thoroughfare: Waterlelielaan
flutter: subThoroughfare: 24
```

**Comment by mvanbeusekom** [comment]
Hello @naumanahmed19, thanks for raising this issue.

In this case the Geolocator plugin uses the native SDK to acquire placemark information which could result in slightly different data:

- On iOS we use the `CLGeocoder` [SDK](https://developer.apple.com/documentation/corelocation/clgeocoder).  
- On Android we use the `Geocoder` [SDK](https://developer.android.com/reference/android/location/Geocoder)

**Comment by naumanahmed19** [comment]
oh no that means there is no way. CLGeocoder is not supporting Pakistan according to this list
https://developer.apple.com/library/archive/technotes/tn2289/_index.html#//apple_ref/doc/uid/DTS40011305-CH1-TNTAG3
