### ISSUE TITLE
position.heading most of the time returns 0 while native apps don't

### ISSUE THREAD

**Issue by dark-chocolate** [BaseflowIT/flutter-geolocator#142]
## 🐛 Bug Report

I am using position.heading() to get the heading and most of the time value returned is 0.0 however other native apps show valid values

### Reproduction steps

```
var locationOptions = LocationOptions(
      accuracy: LocationAccuracy.bestForNavigation,
      distanceFilter: 0,
      timeInterval: 0,
    );

geoLocator.getPositionStream(locationOptions).listen((Position position) {
      print("Heading = ${position.heading}"); // 9 out of 10 times it shows 0
      print("Latitude = ${position.latitude}"); // works fine
      print("Longitude = ${position.longitude}"); // works fine 
    });

```

**Version:** 
2.1.0

**Platform:** 
iOS 12.0.1 (iPhone 6s)
Android 8.0  (Samsung Galaxy S8+)

**Comment by mvanbeusekom** [comment]
@dark-chocolate what happend, is the issue solved?

**Comment by dark-chocolate** [comment]
It's like a dream come true when you respond :), Actually I was seeing the native apps were using compass to show you the direction. However the feature position.heading shows the direction in which you are moving. So, we can't compare the 2. So, my question was irrelevant, I thought of deleting it but couldn't find a way. So, I closed that. 

I would be happy to donate some bucks if you can add the feature to track the location in the background. I know you guys are very busy, its my humble request to put that feature in your todo list on the top and start working on it. My app is completed but because of that feature I can't publish it on the play store.

**Comment by mvanbeusekom** [comment]
@dark-chocolate I am indeed very busy and having a hard time finding more people wishing to contribute so progress is a big slow. 

Running the location updates from the background is on the radar but we need some free time to add it to the code.

**Comment by dark-chocolate** [comment]
I know Android, so I can contribute/help you do the location work from the background using foreground services and other things. I have fine understanding of Services and that's what you need here. I have working code too for Android. 

However I have 0.00% knowledge in iOS, you have to do that on your own.

**Comment by mvanbeusekom** [comment]
I am coming from a Xamarin background and have a reasonable understanding of both platforms. If you fork the repo and submit a pull-request you will automatically be added as contributor to the project (which is something we really really appreciate).

**Comment by dark-chocolate** [comment]
Thank you for telling me. I am happy to become a contributor. Give me like 30 mins, let me create an app in Android.

**Comment by dark-chocolate** [comment]
@mvanbeusekom I was able to make the background location work in iOS. Check [this](https://github.com/BaseflowIT/flutter-geolocator/issues/150) out. Let me know if there is something not working in this. As I said I don't know how to use Github, so there is one change you can make in `LocationServices.swift` file. 

if (shouldRunInBackground) {   // java `if`, I don't know much in swift, so use `if` of swift here
  // code that I put there
}

**Comment by dark-chocolate** [comment]
Now that I tested the app in iPhone 6s (12.0.1) outside, everything was working fine as expected but the direction was 0.0. Don't know why.

**Comment by AlexandreRoba** [comment]
I have a similar problem on IOS with physical phone and simulator. IOS does support directions.
https://developer.apple.com/documentation/corelocation/getting_heading_and_course_information
I'm always getting a heading of 0 :(

**Comment by dark-chocolate** [comment]
@mvanbeusekom has it been fixed? I can see you added a commit, but even the latest version of your package `5.1.2` shows same `0`.

**Comment by dark-chocolate** [comment]
@matheusrezende Using `  geolocator: ^5.1.4`

I tried it in iPhone 6s Real device, everything is working as expected, I have speed, timestamp, latitude, longitude, etc, but heading is still `0.0`. I was moving outdoor, all parameters are working as expected.

**Comment by irjayjay** [comment]
Still an issue in Android, right? It always returns 0 for me.
This thread is old, but I don't see any resolution for Android here.
