### ISSUE TITLE
After upgrading Flutter to Channel beta, v0.11.10, IOS build fails when geolocator ^2.1.0 is used

### ISSUE THREAD

**Issue by jcraane** [BaseflowIT/flutter-geolocator#145]
## 🐛 Bug Report

After upgrading Flutter to Channel beta, v0.11.10, IOS build fails when geolocator ^2.1.0 is used. The build output is as follows:

> Error output from Xcode build:
> ↳
>     ** BUILD FAILED **
> 
> 
> Xcode's output:
> ↳
>     /Users/jamiecraane/develop/tools/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-2.1.2/ios/Classes/PermissionManager.swift:50:59: error: 'openSettingsURLString' has been renamed to 'UIApplicationOpenSettingsURLString'
>                     guard let url = URL(string: UIApplication.openSettingsURLString),
>                                                               ^~~~~~~~~~~~~~~~~~~~~
>                                                               UIApplicationOpenSettingsURLString
>     UIKit.UIApplication:64:22: note: 'openSettingsURLString' was introduced in Swift 4.2
>         public class let openSettingsURLString: String
>                          ^
>     /Users/jamiecraane/develop/tools/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-2.1.2/ios/Classes/PermissionManager.swift:55:45: error: argument labels '(rawValue:)' do not match any available overloads
>                     let optionsKeyDictionary = [UIApplication.OpenExternalURLOptionsKey(rawValue: "universalLinksOnly"): NSNumber(value: true)]
>                                                 ^                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     /Users/jamiecraane/develop/tools/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-2.1.2/ios/Classes/PermissionManager.swift:55:45: note: overloads for 'UIApplication.OpenExternalURLOptionsKey' exist with these partially matching parameter lists: (coder: NSCoder), (stringLiteral: StaticString), (format: NSString, CVarArg...), (string: NSString), (utf8String: UnsafePointer<Int8>), (UTF8String: UnsafePointer<Int8>), (string: String), (contentsOfFile: String), (contentsOf: URL), (contentsOfURL: URL), (cString: UnsafePointer<Int8>), (CString: UnsafePointer<Int8>)
>                     let optionsKeyDictionary = [UIApplication.OpenExternalURLOptionsKey(rawValue: "universalLinksOnly"): NSNumber(value: true)]
>                                                 ^
>     /Users/jamiecraane/develop/tools/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-2.1.2/ios/Classes/PermissionManager.swift:59:91: error: 'openSettingsURLString' has been renamed to 'UIApplicationOpenSettingsURLString'
>                     let success = UIApplication.shared.openURL(URL.init(string: UIApplication.openSettingsURLString)!)
>                                                                                               ^~~~~~~~~~~~~~~~~~~~~
>                                                                                               UIApplicationOpenSettingsURLString
>     UIKit.UIApplication:64:22: note: 'openSettingsURLString' was introduced in Swift 4.2
>         public class let openSettingsURLString: String
>                          ^
>     /Users/jamiecraane/develop/tools/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-2.1.2/ios/Classes/PermissionManager.swift:99:54: error: closure tuple parameter '(key: String, value: Any)' does not support destructuring
>             return Dictionary(uniqueKeysWithValues: input.map { key, value in (UIApplication.OpenExternalURLOptionsKey(rawValue: key), value)})
>                                                                 ^~~~~~~~~~
>                                                                 (arg) -> <#Result#> let (key, value) = arg; return 
> 
> Could not build the application for the simulator.
> Error launching application on iPhone XS.

When removing the gelocator plugin the build fine.

### Expected behavior
IOS project should compile and run on IOS simulator.

### Reproduction steps
Upgrade to Flutter v0.11.10 and create a new Flutter project. Add the geolocator: ^2.1.0 to the pubspec.yaml, get dependencies and try to run the app on an IOS simulator. The build fails with the output specified above.

### Configuration
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.11.10, on Mac OS X 10.14.1 18B75, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] Connected device (1 available)

**Version:** 1.x
2.1.0 

**Platform:** 
- [X] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
@jcraane, pull request to fix this is created and we are going through the last reviews. See PR #144

**Comment by jcraane** [comment]
Thanks!

**Comment by jcraane** [comment]
Unfortunately this did not resolved the issue for me. I created a new Flutter project with geolocator version 2.1.1 and am getting the following error when I build the project for IOS:

> /Users/jamiecraane/develop/tools/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-2.1.2/ios/Classes/PermissionManager.swift:50:59: error: 'openSettingsURLString' has been renamed to 'UIApplicationOpenSettingsURLString'
>                     guard let url = URL(string: UIApplication.openSettingsURLString),
>                                                               ^~~~~~~~~~~~~~~~~~~~~
>                                                               UIApplicationOpenSettingsURLString
>     UIKit.UIApplication:64:22: note: 'openSettingsURLString' was introduced in Swift 4.2
>         public class let openSettingsURLString: String

... Rest is omitted

When I put the offending code in comments (In permission_manager.swift, I do not use that functionality) the build works.

I am happy to provide any information you might need.

**Comment by mvanbeusekom** [comment]
@jcraane, I have just made some tests with a brand new project. I had to make the two changes documented here Flutter#16049 to my `Podfile` (listed in the `ios` folder). After doing so my project compiled correctly.

For you convenience here are the changes:

1. In your `Podfile` make sure you add the line `use_frameworks!` (best is to add this line directly below the `target Runner do` like so:

```
target 'Runner' do
  use_frameworks!
```

2. Also in your `Podfile` make sure you add the line `config.build_settings['SWIFT_VERSION'] = '4.2'` to the `post_installer` block. After adding this line the `post_installer` block should look like this:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '4.2'
    end
  end
end
```

Our hope was that this would no longer be necessary, however unfortunately it still is :(. Please let us know if you experience any further issues.

**Comment by jcraane** [comment]
This indeed solves the issue, thanks!

FYI: I only needed to add the config.build_settings['SWIFT_VERSION'] = '4.2' since the no_frameworks! option was already present (I use Flutter version v0.11.14-pre.2).

**Comment by rasmuschristensen** [comment]
Ohh this saved me time. I did both changes to the POD file and now everything works again. I'm running Flutter 1.0.0. Is this something that is required or due to something temporary? I think it should be added to the read.me

**Comment by ifzm** [comment]
Xcode build done.                                           12.0s
Failed to build iOS app
Error output from Xcode build:
↳
** BUILD FAILED **
Xcode's output:
/Users/jim/.pub-cache/hosted/pub.flutter-io.cn/permission_handler-2.1.2/ios/Classes/PermissionManager.swift:98:118: error: 'OpenExternalURLOptionsKey' is not a member type of 'UIApplication'
fileprivate func convertToUIApplicationOpenExternalURLOptionsKeyDictionary(_ input: [String: Any]) -> [UIApplication.OpenExternalURLOptionsKey: Any] {
~~~~~~~~~~~~~ ^
/Users/jim/.pub-cache/hosted/pub.flutter-io.cn/permission_handler-2.1.2/ios/Classes/PermissionManager.swift:50:45: error: type 'UIApplication' has no member 'openSettingsURLString'
guard let url = URL(string: UIApplication.openSettingsURLString),
^~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~
/Users/jim/.pub-cache/hosted/pub.flutter-io.cn/permission_handler-2.1.2/ios/Classes/PermissionManager.swift:55:45: error: type 'UIApplication' has no member 'OpenExternalURLOptionsKey'
let optionsKeyDictionary = [UIApplication.OpenExternalURLOptionsKey(rawValue: "universalLinksOnly"): NSNumber(value: true)]
^~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jim/.pub-cache/hosted/pub.flutter-io.cn/permission_handler-2.1.2/ios/Classes/PermissionManager.swift:59:77: error: type 'UIApplication' has no member 'openSettingsURLString'
let success = UIApplication.shared.openURL(URL.init(string: UIApplication.openSettingsURLString)!)
^~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~

**Comment by muhammadkhayyam** [comment]
I am using Flutter 1.0.0 , did the modification in POD file , yet receiving the same error .

=== BUILD TARGET geolocator OF PROJECT Pods WITH CONFIGURATION Debug ===
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-2.1.2/ios/Classes/PermissionManager.swift:98:118: error: 'OpenExternalURLOptionsKey' is not a member type of 'UIApplication'
fileprivate func convertToUIApplicationOpenExternalURLOptionsKeyDictionary(_ input: [String: Any]) -> [UIApplication.OpenExternalURLOptionsKey: Any] {
~~~~~~~~~~~~~ ^
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-2.1.2/ios/Classes/PermissionManager.swift:50:45: error: type 'UIApplication' has no member 'openSettingsURLString'
guard let url = URL(string: UIApplication.openSettingsURLString),
..........

**Comment by M-Riyadh** [comment]
@muhammadkhayyam  Try to run `pod install ` after pod file changes

**Comment by a-voyager** [comment]
Flutter 1.0.0 stable not worked after did the modification. +1
