### ISSUE TITLE
Getting error Unexpected token 'await'.

### ISSUE THREAD

**Issue by bsuwirjo** [BaseflowIT/flutter-geolocator#148]
I'm new to flutter and dart so this may be a dumb question but im getting a bunch of errors when trying to get the example code to work. Here is a copy of my error messages. I have tried including dar:async but it does nothing to help. Any help would be appreciated.

Compiler message:
lib/map_page.dart:15:25: Error: Unexpected token 'await'.
    Position position = await Geolocator().getCurrentPosition(desiredAccuracy: LocationAccuracy.high);
                        ^^^^^
lib/map_page.dart:18:29: Error: Unexpected token 'await'.
    LocationResult result = await Geolocation.lastKnownLocation();
                            ^^^^^
lib/map_page.dart:18:5: Error: Type 'LocationResult' not found.
    LocationResult result = await Geolocation.lastKnownLocation();
    ^^^^^^^^^^^^^^
lib/map_page.dart:15:44: Error: A value of type 'dart.async::Future<geolocator::Position>' can't be assigned to a variable of type 'geolocator::Position'.
Try changing the type of the left hand side, or casting the right hand side to 'geolocator::Position'.
    Position position = await Geolocator().getCurrentPosition(desiredAccuracy: LocationAccuracy.high);
                                           ^
lib/map_page.dart:18:35: Error: Getter not found: 'Geolocation'.
    LocationResult result = await Geolocation.lastKnownLocation();
                                  ^^^^^^^^^^^
lib/map_page.dart:18:5: Error: 'LocationResult' isn't a type.
    LocationResult result = await Geolocation.lastKnownLocation();
    ^^^^^^^^^^^^^^
Compiler failed on /home/bsuwirjo/programming/parking/parking/lib/main.dart

**Comment by ibrierley** [comment]
What does the code outside of the command look like, including the sub. Have you included the async package at the top, with an include statement, and have you told the method it's async with an 'async' command before the braces ?

**Comment by bsuwirjo** [comment]
I didn't know you have to include async in the method. I had it included, thanks a lot.
