### ISSUE TITLE
What to do when gps is disabled?

### ISSUE THREAD

**Issue by KiraDiShira** [BaseflowIT/flutter-geolocator#156]
`var status = await geoLocator.checkGeolocationPermissionStatus();`

When status is disabled, what I can do in flutter to enable gps?

The problem is that the first time I use

```
 Position position = await Geolocator()
             .getCurrentPosition(desiredAccuracy: LocationAccuracy.high);
```

even if the gps is disable, there is a dialog who ask me to grant permission for enabling gps.
If later I execute the same code with gps off I have an exception because gps is disabled and no dialog pop up.

What do you suggest to me?

**Comment by ibrierley** [comment]
See if this answer I made before helps, it should open up a dialog window to enable location on Android...

https://stackoverflow.com/questions/53787755/how-to-enable-location-tracking-permissions-from-app-itself/53794339#53794339

**Comment by KiraDiShira** [comment]
Yes, it works. Thank you.
