### ISSUE TITLE
only on release, when run geolocator , Exit from app

### ISSUE THREAD

**Issue by htetwaiyan** [BaseflowIT/flutter-geolocator#161]
### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
Did you include the required permissions in the `Info.plist`? You should at least add the following lines (more information can be found in [Apples documentation](https://developer.apple.com/documentation/corelocation/choosing_the_authorization_level_for_location_services)):

```
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>Allow this App to access your location only when the app is in use?</string>
```

If the above is not the problem please supply additional information. At the bare minimum provide reproduction steps and fill in the complete "Bug Report" form. Even better would be an example application reproducing this behaviour. 

I have tested this with the example application on iOS (in release mode) and experienced no problems. I could request the current location and also listen to the location stream and cancel it when I was done. Opening App settings was also not a problem.
