### ISSUE TITLE
GoogleApiAvailabilityPlugin.m:2:9: fatal error: 'google_api_availability/google_api_availability-Swift.h' file not found

### ISSUE THREAD

**Issue by delphiy** [BaseflowIT/flutter-geolocator#162]
GoogleApiAvailabilityPlugin.m:2:9: fatal error: 'google_api_availability/google_api_availability-Swift.h' file not found
    #import <google_api_availability/google_api_availability-Swift.h>

**Comment by BarbaricGamester** [comment]
@delphiy Where you able to solve this issue? and how?

**Comment by BarbaricGamester** [comment]
Thanks, it worked!

**Comment by htetwaiyan** [comment]
but it was a problem only with one signal
