### ISSUE TITLE
fatal error: 'geolocator/geolocator-Swift.h' file not found

### ISSUE THREAD

**Issue by delphiy** [BaseflowIT/flutter-geolocator#163]
fatal error: 'geolocator/geolocator-Swift.h' file not found

**Comment by delphiy** [comment]
Hi,


Go to Ios/Podfile

add the following line:
use_frameworks! # required by Geolocator

Like the following

Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
referring to absolute paths on developers' machines.
use_frameworks! # required by Geolocator
system('rm -rf .symlinks')
system('mkdir -p .symlinks/plugins')

After this add
config.build_settings['SWIFT_VERSION'] = '4.2'

Like the following:

post_install do |installer|
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config|
config.build_settings['ENABLE_BITCODE'] = 'NO'
config.build_settings['SWIFT_VERSION'] = '4.2'
end
end
end

**Comment by marcuslma** [comment]
Still this configuration necessary in version 3.0.1?

**Comment by htetwaiyan** [comment]
Thank you
