### ISSUE TITLE
A package itself may not list itself as a dependency

### ISSUE THREAD

**Issue by ljfreelancer88** [BaseflowIT/flutter-geolocator#165]
## 💬 Questions and Help

I did try to install this package to newly created flutter but this error "A package itself may not list itself as a dependency" slap my face. It's my first time to encounter this. I want to know what that error is all about and how can I fix the issue. By the way Thank You for your contribution to flutter community.

**Comment by ibrierley** [comment]
Have you called your own project or library geolocator or similar ?

**Comment by ljfreelancer88** [comment]
I named the project "geo" and added gelocator in my yml file then flutter packages get. I used the latest flutter SDK and windows 7.

**Comment by ljfreelancer88** [comment]
It's working now. I created new project "ember" and installed geolocator in my yml. Because as far as I remember, the name of the project was geolocator then i renamed w/ geo but still the same problem.
