### ISSUE TITLE
geolocator: 2.1.1 Android resource linking failed

### ISSUE THREAD

**Issue by aswanthrc** [BaseflowIT/flutter-geolocator#185]
While adding geolocator: 2.1.1 to my project i am getting this error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  Output:  /home/aswanth/AndroidStudioProjects/FlutterWorkSpace/middi_flutter/build/app/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:107: error: resource android:attr/fontVariationSettings not found.
  /home/aswanth/AndroidStudioProjects/FlutterWorkSpace/middi_flutter/build/app/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:107: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

  Command: /home/aswanth/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-linux.jar/499c535b8df9cd1772a724d7bbcc8fe8/aapt2-3.2.1-4818971-linux/aapt2 link -I\
          /home/aswanth/Android/Sdk/platforms/android-27/android.jar\
          --manifest\
          /home/aswanth/AndroidStudioProjects/FlutterWorkSpace/middi_flutter/build/app/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml\
          -o\
          /home/aswanth/AndroidStudioProjects/FlutterWorkSpace/middi_flutter/build/app/intermediates/processed_res/debug/processDebugResources/out/resources-debug.ap_\
          -R\
          @/home/aswanth/AndroidStudioProjects/FlutterWorkSpace/middi_flutter/build/app/intermediates/incremental/processDebugResources/resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          /home/aswanth/AndroidStudioProjects/FlutterWorkSpace/middi_flutter/build/app/generated/not_namespaced_r_class_sources/debug/processDebugResources/r\
          --proguard-main-dex\
          /home/aswanth/AndroidStudioProjects/FlutterWorkSpace/middi_flutter/build/app/intermediates/legacy_multidex_aapt_derived_proguard_rules/debug/processDebugResources/manifest_keep.txt\
          --custom-package\
          com.application.middi\
          -0\
          apk\
          --output-text-symbols\
          /home/aswanth/AndroidStudioProjects/FlutterWorkSpace/middi_flutter/build/app/intermediates/symbols/debug/R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-linux Daemon #0
  Output:  /home/aswanth/.gradle/caches/transforms-1/files-1.1/core-1.0.1.aar/647821bdf56efd0fba7244d83e3e3d6a/res/values/values.xml:89:5-125:25: AAPT: error: resource android:attr/fontVariationSettings not found.

  /home/aswanth/.gradle/caches/transforms-1/files-1.1/core-1.0.1.aar/647821bdf56efd0fba7244d83e3e3d6a/res/values/values.xml:89:5-125:25: AAPT: error: resource android:attr/ttcIndex not found.

  error: failed linking references.
  Command: /home/aswanth/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-linux.jar/499c535b8df9cd1772a724d7bbcc8fe8/aapt2-3.2.1-4818971-linux/aapt2 link -I\
          /home/aswanth/Android/Sdk/platforms/android-27/android.jar\
          --manifest\
          /home/aswanth/AndroidStudioProjects/FlutterWorkSpace/middi_flutter/build/app/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml\
          -o\
          /home/aswanth/AndroidStudioProjects/FlutterWorkSpace/middi_flutter/build/app/intermediates/processed_res/debug/processDebugResources/out/resources-debug.ap_\
          -R\
          @/home/aswanth/AndroidStudioProjects/FlutterWorkSpace/middi_flutter/build/app/intermediates/incremental/processDebugResources/resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          /home/aswanth/AndroidStudioProjects/FlutterWorkSpace/middi_flutter/build/app/generated/not_namespaced_r_class_sources/debug/processDebugResources/r\
          --proguard-main-dex\
          /home/aswanth/AndroidStudioProjects/FlutterWorkSpace/middi_flutter/build/app/intermediates/legacy_multidex_aapt_derived_proguard_rules/debug/processDebugResources/manifest_keep.txt\
          --custom-package\
          com.application.middi\
          -0\
          apk\
          --output-text-symbols\
          /home/aswanth/AndroidStudioProjects/FlutterWorkSpace/middi_flutter/build/app/intermediates/symbols/debug/R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-linux Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by bali-ibrahim** [comment]
I am having similar issue as of yesterday. Including this package seems to break the build as in:

```
dependencies:
  geolocator: ^2.1.1
```

 here's the stacktrace shown when trying to debug the geolocator prototype code:

```
Launching lib\main.dart on [Attached Phone Name] in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  Output:  D:\Users\username\Documents\CompanyName\ProjectName\RepositoryName\poc_location\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:101: error: resource android:attr/fontVariationSettings not found.
  D:\Users\username\Documents\CompanyName\ProjectName\RepositoryName\poc_location\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:101: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

  Command: C:\Users\username\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\2b326e55429f04e1c45dcdaf64384bb2\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
          C:\Users\username\AppData\Local\Android\sdk\platforms\android-27\android.jar\
          --manifest\
          D:\Users\username\Documents\CompanyName\ProjectName\RepositoryName\poc_location\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          D:\Users\username\Documents\CompanyName\ProjectName\RepositoryName\poc_location\build\app\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @D:\Users\username\Documents\CompanyName\ProjectName\RepositoryName\poc_location\build\app\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          D:\Users\username\Documents\CompanyName\ProjectName\RepositoryName\poc_location\build\app\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --custom-package\
          com.example.poclocation\
          -0\
          apk\
          --output-text-symbols\
          D:\Users\username\Documents\CompanyName\ProjectName\RepositoryName\poc_location\build\app\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
  Output:  C:\Users\username\.gradle\caches\transforms-1\files-1.1\core-1.0.1.aar\0235e1ca304bda1ab620d211c370b5a1\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/fontVariationSettings not found.

  C:\Users\username\.gradle\caches\transforms-1\files-1.1\core-1.0.1.aar\0235e1ca304bda1ab620d211c370b5a1\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/ttcIndex not found.

  error: failed linking references.
  Command: C:\Users\username\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\2b326e55429f04e1c45dcdaf64384bb2\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
          C:\Users\username\AppData\Local\Android\sdk\platforms\android-27\android.jar\
          --manifest\
          D:\Users\username\Documents\CompanyName\ProjectName\RepositoryName\poc_location\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          D:\Users\username\Documents\CompanyName\ProjectName\RepositoryName\poc_location\build\app\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @D:\Users\username\Documents\CompanyName\ProjectName\RepositoryName\poc_location\build\app\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          D:\Users\username\Documents\CompanyName\ProjectName\RepositoryName\poc_location\build\app\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --custom-package\
          com.example.poclocation\
          -0\
          apk\
          --output-text-symbols\
          D:\Users\username\Documents\CompanyName\ProjectName\RepositoryName\poc_location\build\app\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 33s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

```

---

Also here's the stacktrace after calling `flutter clean && flutter create . ` and then debugging:

```
Launching lib\main.dart on [Attached Phone Name] in debug mode...

Compiler message:
file:///D:/src/flutter/.pub-cache/hosted/pub.dartlang.org/google_api_availability-1.0.5/lib/google_api_availability.dart:39:55: Error: Expected 0 type arguments.
    final dynamic availability = await _methodChannel.invokeMethod<String>(
                                                      ^
Compiler failed on D:\Users\username\Documents\CompanyName\ProjectName\RepositoryName\poc_location\lib\main.dart
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)


```

**Comment by harsh5400** [comment]
same issue. Any solution?

**Comment by ugurcany** [comment]
Same here!

**Comment by Noyal** [comment]
If you want to make it work locally, 
go to the .pub_cache/hosted and change the pubspec.yaml of geolocator

`
dependencies:
  meta: "^1.0.5"
  flutter:
    sdk: flutter
  permission_handler: "2.1.2"
  google_api_availability: "1.0.4"
`

because of the caret ^, it is taking the google_api_availability latest, which is migrated to android x.

See if this helps.

**Comment by ugurcany** [comment]
I added the following lines to my project's pubspec.yaml, and it works now:

**Comment by Noyal** [comment]
@ugurcany Yeah, thats better

**Comment by aswanthrc** [comment]
> I added the following lines to my project's `pubspec.yaml` under dependencies, and it works now:
> 
> ```
>   permission_handler: "2.1.2"
>   google_api_availability: "1.0.4"
> ```

this one solved my issue

**Comment by mvanbeusekom** [comment]
Thank you @ugurcany and @Noyal, you are correct we updated the google_availabitity plugin to AndroidX and didn't realize this would be a breaking change (and thus didn't bump the major version number).

We just release version 3.0.0 of the Geolocator plugin which supports AndroidX and can be used freely. Just make sure you also migrate your App to support AndroidX (instructions can be found here: https://flutter.io/docs/development/packages-and-plugins/androidx-compatibility).

**Comment by mhmoudsabry** [comment]
work for me thanks

**Comment by langerkirill** [comment]
This breaks the ios build though

**Comment by kbrmimbyl** [comment]
Everyone on this thread -- you guys just saved a life. Mine.
