### ISSUE TITLE
Android won't compile with error of bunch files doesnt not exist

### ISSUE THREAD

**Issue by comeonbuddy** [BaseflowIT/flutter-geolocator#187]
Android compile fails with error, do you have any idea why is this happening?

`/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/android/src/main/java/com/baseflow/flutter/plugin/geolocator/tasks/LocationUpdatesUsingLocationManagerTask.java:13: error: package com.google.android.gms.common.util does not exist
import com.google.android.gms.common.util.Strings;
                                         ^
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/android/src/main/java/com/baseflow/flutter/plugin/geolocator/tasks/LocationUpdatesUsingLocationServicesTask.java:5: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/android/src/main/java/com/baseflow/flutter/plugin/geolocator/tasks/LocationUpdatesUsingLocationServicesTask.java:8: error: package com.google.android.gms.location does not exist
import com.google.android.gms.location.FusedLocationProviderClient;
                                      ^
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/android/src/main/java/com/baseflow/flutter/plugin/geolocator/tasks/LocationUpdatesUsingLocationServicesTask.java:9: error: package com.google.android.gms.location does not exist
import com.google.android.gms.location.LocationCallback;
                                      ^
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/android/src/main/java/com/baseflow/flutter/plugin/geolocator/tasks/LocationUpdatesUsingLocationServicesTask.java:10: error: package com.google.android.gms.location does not exist
import com.google.android.gms.location.LocationRequest;
                                      ^
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/android/src/main/java/com/baseflow/flutter/plugin/geolocator/tasks/LocationUpdatesUsingLocationServicesTask.java:11: error: package com.google.android.gms.location does not exist
import com.google.android.gms.location.LocationResult;
                                      ^
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/android/src/main/java/com/baseflow/flutter/plugin/geolocator/tasks/LocationUpdatesUsingLocationServicesTask.java:12: error: package com.google.android.gms.location does not exist
import com.google.android.gms.location.LocationServices;
                                      ^
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/android/src/main/java/com/baseflow/flutter/plugin/geolocator/tasks/LocationUpdatesUsingLocationServicesTask.java:13: error: package com.google.android.gms.tasks does not exist
import com.google.android.gms.tasks.OnCompleteListener;
                                   ^
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/android/src/main/java/com/baseflow/flutter/plugin/geolocator/tasks/LocationUpdatesUsingLocationServicesTask.java:14: error: package com.google.android.gms.tasks does not exist
import com.google.android.gms.tasks.Task;
                                   ^
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/android/src/main/java/com/baseflow/flutter/plugin/geolocator/tasks/LocationUpdatesUsingLocationServicesTask.java:21: error: cannot find symbol
    private final FusedLocationProviderClient mFusedLocationProviderClient;
                  ^
  symbol:   class FusedLocationProviderClient
  location: class LocationUpdatesUsingLocationServicesTask
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/android/src/main/java/com/baseflow/flutter/plugin/geolocator/tasks/LocationUpdatesUsingLocationServicesTask.java:22: error: cannot find symbol
    private final LocationCallback mLocationCallback;
                  ^
  symbol:   class LocationCallback
  location: class LocationUpdatesUsingLocationServicesTask
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/android/src/main/java/com/baseflow/flutter/plugin/geolocator/tasks/LocationUpdatesUsingLocationServicesTask.java:83: error: cannot find symbol
    private LocationRequest createLocationRequest() {
            ^
  symbol:   class LocationRequest
  location: class LocationUpdatesUsingLocationServicesTask
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/android/src/main/java/com/baseflow/flutter/plugin/geolocator/tasks/LastKnownLocationUsingLocationServicesTask.java:4: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/android/src/main/java/com/baseflow/flutter/plugin/geolocator/tasks/LastKnownLocationUsingLocationServicesTask.java:7: error: package com.google.android.gms.location does not exist
import com.google.android.gms.location.FusedLocationProviderClient;
                                      ^
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/android/src/main/java/com/baseflow/flutter/plugin/geolocator/tasks/LastKnownLocationUsingLocationServicesTask.java:8: error: package com.google.android.gms.location does not exist
import com.google.android.gms.location.LocationServices;
                                      ^
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/android/src/main/java/com/baseflow/flutter/plugin/geolocator/tasks/LastKnownLocationUsingLocationServicesTask.java:9: error: package com.google.android.gms.tasks does not exist
import com.google.android.gms.tasks.OnFailureListener;
                                   ^
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/android/src/main/java/com/baseflow/flutter/plugin/geolocator/tasks/LastKnownLocationUsingLocationServicesTask.java:10: error: package com.google.android.gms.tasks does not exist
import com.google.android.gms.tasks.OnSuccessListener;
                                   ^
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/android/src/main/java/com/baseflow/flutter/plugin/geolocator/tasks/LastKnownLocationUsingLocationServicesTask.java:15: error: cannot find symbol
    private final FusedLocationProviderClient mFusedLocationProviderClient;
                  ^
  symbol:   class FusedLocationProviderClient
  location: class LastKnownLocationUsingLocationServicesTask
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/android/src/main/java/com/baseflow/flutter/plugin/geolocator/tasks/LocationUpdatesUsingLocationManagerTask.java:42: error: cannot find symbol
        if(Strings.isEmptyOrWhitespace(mActiveProvider)) {
           ^
  symbol:   variable Strings
  location: class LocationUpdatesUsingLocationManagerTask
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/android/src/main/java/com/baseflow/flutter/plugin/geolocator/tasks/LocationUpdatesUsingLocationManagerTask.java:121: error: cannot find symbol
        if(Strings.isEmptyOrWhitespace(provider)) {
           ^
  symbol:   variable Strings
  location: class LocationUpdatesUsingLocationManagerTask
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/android/src/main/java/com/baseflow/flutter/plugin/geolocator/tasks/LocationUpdatesUsingLocationServicesTask.java:30: error: cannot find symbol
        mFusedLocationProviderClient = LocationServices.getFusedLocationProviderClient(taskContext.getAndroidContext());
                                       ^
  symbol:   variable LocationServices
  location: class LocationUpdatesUsingLocationServicesTask
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/android/src/main/java/com/baseflow/flutter/plugin/geolocator/tasks/LocationUpdatesUsingLocationServicesTask.java:31: error: cannot find symbol
        mLocationCallback = new LocationCallback() {
                                ^
  symbol:   class LocationCallback
  location: class LocationUpdatesUsingLocationServicesTask
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/android/src/main/java/com/baseflow/flutter/plugin/geolocator/tasks/LocationUpdatesUsingLocationServicesTask.java:60: error: cannot find symbol
                .addOnCompleteListener(new OnCompleteListener<Void>() {
                                           ^
  symbol:   class OnCompleteListener
  location: class LocationUpdatesUsingLocationServicesTask
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/android/src/main/java/com/baseflow/flutter/plugin/geolocator/tasks/LocationUpdatesUsingLocationServicesTask.java:84: error: cannot find symbol
        LocationRequest locationRequest = new LocationRequest();
        ^
  symbol:   class LocationRequest
  location: class LocationUpdatesUsingLocationServicesTask
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/android/src/main/java/com/baseflow/flutter/plugin/geolocator/tasks/LocationUpdatesUsingLocationServicesTask.java:84: error: cannot find symbol
        LocationRequest locationRequest = new LocationRequest();
                                              ^
  symbol:   class LocationRequest
  location: class LocationUpdatesUsingLocationServicesTask
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/android/src/main/java/com/baseflow/flutter/plugin/geolocator/tasks/LocationUpdatesUsingLocationServicesTask.java:93: error: cannot find symbol
                locationRequest.setPriority(LocationRequest.PRIORITY_LOW_POWER);
                                            ^
  symbol:   variable LocationRequest
  location: class LocationUpdatesUsingLocationServicesTask
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/android/src/main/java/com/baseflow/flutter/plugin/geolocator/tasks/LocationUpdatesUsingLocationServicesTask.java:96: error: cannot find symbol
                locationRequest.setPriority(LocationRequest.PRIORITY_BALANCED_POWER_ACCURACY);
                                            ^
  symbol:   variable LocationRequest
  location: class LocationUpdatesUsingLocationServicesTask
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/android/src/main/java/com/baseflow/flutter/plugin/geolocator/tasks/LocationUpdatesUsingLocationServicesTask.java:99: error: cannot find symbol
                locationRequest.setPriority(LocationRequest.PRIORITY_HIGH_ACCURACY);
                                            ^
  symbol:   variable LocationRequest
  location: class LocationUpdatesUsingLocationServicesTask
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/android/src/main/java/com/baseflow/flutter/plugin/geolocator/tasks/LastKnownLocationUsingLocationServicesTask.java:20: error: cannot find symbol
        mFusedLocationProviderClient = LocationServices.getFusedLocationProviderClient(taskContext.getAndroidContext());
                                       ^
  symbol:   variable LocationServices
  location: class LastKnownLocationUsingLocationServicesTask
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/android/src/main/java/com/baseflow/flutter/plugin/geolocator/tasks/LastKnownLocationUsingLocationServicesTask.java:38: error: cannot find symbol
                .addOnFailureListener(new OnFailureListener() {
                                          ^
  symbol:   class OnFailureListener
  location: class LastKnownLocationUsingLocationServicesTask
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/android/src/main/java/com/baseflow/flutter/plugin/geolocator/tasks/LastKnownLocationUsingLocationServicesTask.java:26: error: cannot find symbol
                .addOnSuccessListener(new OnSuccessListener<Location>() {
                                          ^
  symbol:   class OnSuccessListener
  location: class LastKnownLocationUsingLocationServicesTask
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.`

flutter doctor

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] Connected device (1 available)

• No issues found!
`

**Comment by mvanbeusekom** [comment]
@comeonbuddy, this is most likely caused because we accidentally introduced a breaking change in the google_availability_api plugin. We updated it to support AndroidX but unfortunately treated it as a small update so we only increased the patch number of the version (1.0.4 to 1.0.5). 

There are two possible solutions:

__Option 1:__
Upgrade to the (just released) Geolocator  version 3.0.0 and make sure your app also is migrated to support AndroidX (see [here](https://flutter.io/docs/development/packages-and-plugins/developing-packages) for details);

__Option 2:__
Add the following dependencies to your `pubspec.yaml` file (which ensures a specific version of the plugins are used):

```
  permission_handler: "2.1.2"
  google_api_availability: "1.0.4"
```

Note, this only works for geolocator version 2.1.1 (if you upgrade to version 3.0.0, you should remove the two lines again).

Our apologies for the inconvenience.
