### ISSUE TITLE
Compilation error in android

### ISSUE THREAD

**Issue by Aanu1995** [BaseflowIT/flutter-geolocator#188]
## 🐛 Bug Report

C:\flutter_windows_v1.0.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\geolocator-2.1.1\android\src\main\java\com\baseflow\flutter\plugin\geolocator\tasks\LastKnownLocationUsingLocationServicesTask.java:4: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
C:\flutter_windows_v1.0.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\geolocator-2.1.1\android\src\main\java\com\baseflow\flutter\plugin\geolocator\tasks\LocationUpdatesUsingLocationServicesTask.java:5: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
C:\flutter_windows_v1.0.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\geolocator-2.1.1\android\src\main\java\com\baseflow\flutter\plugin\geolocator\tasks\LastKnownLocationUsingLocationServicesTask.java:40: error: cannot find symbol
                    public void onFailure(@NonNull Exception e) {
                                           ^
  symbol: class NonNull
C:\flutter_windows_v1.0.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\geolocator-2.1.1\android\src\main\java\com\baseflow\flutter\plugin\geolocator\tasks\LocationUpdatesUsingLocationServicesTask.java:62: error: cannot find symbol
                    public void onComplete(@NonNull Task<Void> task) {
                                            ^
  symbol: class NonNull
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors
         *********************************************************
WARNING: This version of cloud_firestore will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':geolocator:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 32s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by Aanu1995** [comment]
Please, does anyone know why these errors. Could it be because the library has not been migrated to android X

**Comment by mvanbeusekom** [comment]
@Aanu1995, this is most probably the case indeed. We have just released version 3.0.0 of the plugin which has support for AndroidX.
