### ISSUE TITLE
AndroidX error in geolocator version 3. 

### ISSUE THREAD

**Issue by kasonde** [BaseflowIT/flutter-geolocator#194]
## 🔙 Regression

After creating a new project, I installed permission_handler and geolocator, it seems geolocator won't work. Here's the error I get.

`
D8: Program type already present: android.support.v4.os.ResultReceiver$1

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/4.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/5.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/6.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/7.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/8.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/9.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/10.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/11.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/12.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/13.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/14.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/15.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/16.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/17.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/18.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/19.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/30.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/35.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/40.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/45.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/50.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/55.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/60.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/65.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/70.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/75.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/80.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/85.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/90.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/95.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/100.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/105.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/110.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/115.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/120.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/125.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/130.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/135.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/140.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/145.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/150.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/155.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/160.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/165.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/170.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/175.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/180.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/185.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/190.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/195.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/200.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/205.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/210.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/215.jar
  Program type already present: android.support.v4.os.ResultReceiver$1
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1
`
### Reproduction steps
Create a new flutter project based on master branch and newest version. 
Install permission_handler and this lib as well
### Configuration

**Version:** 3.0.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
@kasonde you manually need to update the project to AndroidX. This consists out of the following steps:

1. Add the following to your "gradle.properties" file:

```
android.useAndroidX=true
android.enableJetifier=true
```
2. Make sure you set the `compileSdkVersion` in your "android/app/build.gradle" file to 28:

```
android {
  compileSdkVersion 28

  ...
}
```
3. Make sure you replace all the `android.` dependencies to their AndroidX counterparts (a full list can be found here: https://developer.android.com/jetpack/androidx/migrate).

**Comment by kasonde** [comment]
Hi @mvanbeusekom Thanks for the tip. I can confirm that that helps alleviate all the problems.
