### ISSUE TITLE
Public constructor for Position

### ISSUE THREAD

**Issue by nkalscheuer** [BaseflowIT/flutter-geolocator#195]
## 🚀 Feature Requests

Add a public constructor to the Position model class.

Not having a public constructor for the position model makes it very difficult to make a fake position stream for unit/widget testing. 

It doesn't have to be misleading, maybe just make the constructor call like Position.fake(this.latitude,...).

- [ X] :iphone: iOS
- [ X] :robot: Android

**Comment by mvanbeusekom** [comment]
@nkalscheuer this will be supported in the next release, we already merged PR #193 from a contributor. This version will be released in the coming days.
