### ISSUE TITLE
android build fails (program type already present)

### ISSUE THREAD

**Issue by eliburgi** [BaseflowIT/flutter-geolocator#197]
I´ve added the geolocator: ^3.0.0 dependency to my pubspec.yaml. Then I´ve created a simple widget that displays the current location and tried to run the app. Unfortunately, I get the following error: 

Launching lib\main.dart on Android SDK built for x86 in debug mode...
D8: Program type already present: android.support.v4.os.ResultReceiver$1

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\4.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\5.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\6.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\7.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\8.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\9.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\10.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\11.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\12.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\13.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\14.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\15.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\16.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\17.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\18.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\19.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\20.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\21.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\22.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\23.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\24.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\25.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\26.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\27.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\28.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\29.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\30.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\31.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\32.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\33.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\34.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\35.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\36.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\37.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\38.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\39.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\40.jar,C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\41.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\42.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\43.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\44.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\45.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\46.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\47.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\48.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\49.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\50.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\51.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\52.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\53.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\54.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\55.jar, C:\Users\Elias\Desktop\App_Development\Flutter\GPS_Demo\gps_demo\build\app\intermediates\transforms\dexBuilder\debug\56.jar, C:\Users\Elias\Deskt

 Program type already present: android.support.v4.os.ResultReceiver$1
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 9s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleDebug failed with exit code 1

**Comment by mvanbeusekom** [comment]
@eliburgi please migrate your project to AndroidX. See also the following issues:

- #186
- https://github.com/BaseflowIT/flutter-geolocator/issues/189#issuecomment-463771448
