### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by singhbhavneet** [BaseflowIT/flutter-geolocator#200]
### Android resource linking failed
  Output:  E:\onappr\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:101: error: resource android:attr/fontVariationSettings not found.
  E:\onappr\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:101: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

**Comment by mikerobi** [comment]
I have both of those errors plus 2 additional ones.

> build\app\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
> build\app\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.

**Comment by iambudi** [comment]
Using 3.0.0
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives

The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.

**Comment by aumb** [comment]
If you want to use 3.0.0:

1) Go to android/app/build.gradle file and change 
- replace current testInstrumentationRunner with "androidx.test.runner.AndroidJUnitRunner"
- replace the first androidTestImplementation with 'androidx.test:runner:1.1.2-alpha01'
- replace the second androidTestImplementation with  'androidx.test.espresso:espresso-core:3.1.2-alpha01'

2) Go to android/gradle.properties
- add these 2 lines android.enableJetifier=true android.useAndroidX=true

P.S you might have to change
-compiled version to 28 
-targetsdkversion to 28
but you need to have an emulator/device that runs 9.0

**Comment by mikerobi** [comment]
@aumb Then what do you do if you need to sport 9.0 and earlier versions?

**Comment by mvanbeusekom** [comment]
@mikerobi this is all backwards compatible, you can set the `compileSdkVersion` to 28 and leave the `targetSdkVersion` to 27 or lower if you prever. 

Also there were some problems with wrong dependencies so it might be good to update to Geolocator version 3.0.1
