### ISSUE TITLE
How to stop PositionStream after getting location updates.

### ISSUE THREAD

**Issue by phprad** [BaseflowIT/flutter-geolocator#201]
## 💬 Questions and Help
How to stop PositionStream after getting location updates.

```
var geolocator = Geolocator();
         var locationOptions = LocationOptions(accuracy: LocationAccuracy.high, distanceFilter: 1, timeInterval: 1000);
         geolocator.getPositionStream(locationOptions).listen( (Position position) {
           if(position.accuracy > 10 ){
              // I want to cancel the position update
           }
 });
```

**Comment by wagnerdelima** [comment]
Do you actually manage to get the location? We've been creating issues for locations not retrieved.

**Comment by phprad** [comment]
Yes, am able to get the location updates. using 
dependencies:
  geolocator: '^3.0.0'

**Comment by mvanbeusekom** [comment]
You should call the `cancel` method on the `StreamSubscription` instance that is returned when you called the `listen` method.

Something like this:

```dart
var geolocator = Geolocator();
var locationOptions = LocationOptions(accuracy: LocationAccuracy.high, distanceFilter: 1, timeInterval: 1000);
var subscription = geolocator.getPositionStream(locationOptions).listen( (Position position) {
           if(position.accuracy > 10 ){
              // I want to cancel the position update
              subscription.cancel();
           }
 });
```
You can also look at the example project (exact code is here: https://github.com/BaseflowIT/flutter-geolocator/blob/4601adc081c8df2831f676a86d8545a4680115a6/example/lib/pages/location_stream_widget.dart#L17)
