### ISSUE TITLE
The following dependencies do not satisfy the required version: project ':google_api_availability' 

### ISSUE THREAD

**Issue by nicolasjon** [BaseflowIT/flutter-geolocator#202]
## 🔙 Regression

After recent update of Flutter plugin 
The following dependencies do not satisfy the required version:
project ':google_api_availability' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

Know issue
[https://stackoverflow.com/questions/54693595/flutter-the-android-gradle-plugin-supports-only-kotlin-gradle-plugin-version-1](url)

### Old (and correct) behaviour
Android builds

### Current behaviour

Android build breaks -
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher.
The following dependencies do not satisfy the required version:
project ':google_api_availability' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

### Reproduction steps
Android build

### Configuration

**Version:** 3.0.0

**Platform:** 
- [ ] :iphone: iOS
- [ x] :robot: Android

**Comment by nicolasjon** [comment]
A couple of temporary work rounds have been described

Fixing the versions until google_api_availability is updated. 
geolocator: 3.0.0               # AndroidX - Breaking! 
google_api_availability: 1.0.6  # Geolocator Dependency. 
meta: 1.1.6                     # Geolocator Dependency. 
permission_handler: 2.2.0       # Geolocator & Meta Dependency.

Is what I did, and that worked with the latest 3.3.1 of the Android Gradle build plugin  

or using and older version of Android Gradle build plugin - But for me at least this just broke other things!

Info here may be duplicated with other issues, please use revise as is helpful.

**Comment by bicho19** [comment]
Thank you, this worked for me.

> A couple of temporary work rounds have been described
> 
> Fixing the versions until google_api_availability is updated.
> geolocator: 3.0.0 # AndroidX - Breaking!
> google_api_availability: 1.0.6 # Geolocator Dependency.
> meta: 1.1.6 # Geolocator Dependency.
> permission_handler: 2.2.0 # Geolocator & Meta Dependency.
> 
> Is what I did, and that worked with the latest 3.3.1 of the Android Gradle build plugin
> 
> or using and older version of Android Gradle build plugin - But for me at least this just broke other things!
> 
> Info here may be duplicated with other issues, please use revise as is helpful.

**Comment by tsjly** [comment]
jump in this file . ../flutter/.pub-cache/hosted/pub.dartlang.org/google_api_availability-1.0.6+1/android/build.gradle
replace ext.kotlin_version = '1.3.21'

**Comment by juanjoserodrigolazaro** [comment]
@nicolasjon answer didnt work for me :(

**Comment by mvanbeusekom** [comment]
@nicolasjon this should be solved in version 3.0.1 where we removed all dependecies on Kotlin (using version 2.0.0 of the `google_api_availability` plugin and version 3.0.0 of the `permission_handler`)

**Comment by nicolasjon** [comment]
Works. Thanks! Nicolas
