### ISSUE TITLE
android x issues

### ISSUE THREAD

**Issue by aidooyaw1992** [BaseflowIT/flutter-geolocator#204]
## 🔙 Regression

i cant use this plugin anymore
### Current behavior

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  Output:  C:\Users\LENOVO\Documents\flutter_projects\geolocatorapp\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  C:\Users\LENOVO\Documents\flutter_projects\geolocatorapp\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  C:\Users\LENOVO\Documents\flutter_projects\geolocatorapp\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:905: error: resource android:attr/fontVariationSettings not found.
  C:\Users\LENOVO\Documents\flutter_projects\geolocatorapp\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:905: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

  Command: C:\Users\LENOVO\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\71cfcfcc2f8af53a0b6b48c98548975b\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
          C:\Users\LENOVO\AppData\Local\Android\Sdk\platforms\android-27\android.jar\
          --manifest\
          C:\Users\LENOVO\Documents\flutter_projects\geolocatorapp\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          C:\Users\LENOVO\Documents\flutter_projects\geolocatorapp\build\app\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @C:\Users\LENOVO\Documents\flutter_projects\geolocatorapp\build\app\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          C:\Users\LENOVO\Documents\flutter_projects\geolocatorapp\build\app\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --custom-package\
          com.example.geolocatorapp\
          -0\
          apk\
          --output-text-symbols\
          C:\Users\LENOVO\Documents\flutter_projects\geolocatorapp\build\app\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
  Output:  C:\Users\LENOVO\.gradle\caches\transforms-1\files-1.1\appcompat-1.0.1.aar\f492a862a144a36d8399d1a1c7eee7ae\res\values-v28\values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCornerRadius not found.

  C:\Users\LENOVO\Documents\flutter_projects\geolocatorapp\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:11: AAPT: error: resource android:attr/dialogCornerRadius not found.

  C:\Users\LENOVO\.gradle\caches\transforms-1\files-1.1\core-1.0.1.aar\ea1369d73960384fe1be9faa0f5020b0\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/fontVariationSettings not found.

  C:\Users\LENOVO\.gradle\caches\transforms-1\files-1.1\core-1.0.1.aar\ea1369d73960384fe1be9faa0f5020b0\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/ttcIndex not found.

  error: failed linking references.
  Command: C:\Users\LENOVO\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\71cfcfcc2f8af53a0b6b48c98548975b\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
          C:\Users\LENOVO\AppData\Local\Android\Sdk\platforms\android-27\android.jar\
          --manifest\
          C:\Users\LENOVO\Documents\flutter_projects\geolocatorapp\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          C:\Users\LENOVO\Documents\flutter_projects\geolocatorapp\build\app\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @C:\Users\LENOVO\Documents\flutter_projects\geolocatorapp\build\app\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          C:\Users\LENOVO\Documents\flutter_projects\geolocatorapp\build\app\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --custom-package\
          com.example.geolocatorapp\
          -0\
          apk\
          --output-text-symbols\
          C:\Users\LENOVO\Documents\flutter_projects\geolocatorapp\build\app\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 53s

Gradle task 'assembleDebug'... Done                         53.7s
Gradle task assembleDebug failed with exit code 1
### Configuration

**Version:** 3.0.0

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by joaquinperaza** [comment]
Same here

**Comment by iambudi** [comment]
I solved this issue by opening the gradle script of google api availability in android studio and change to compileSdkVersion 28 and 
classpath 'com.android.tools.build:gradle:3.3.1'
Save -> Build -> Make Module.

**Comment by aidooyaw1992** [comment]
Did it work when u built it in release mode?

**Comment by aidooyaw1992** [comment]
It has worked now. Thank you very much. Can you please explain why

**Comment by iambudi** [comment]
Yes it works on release mode as well.

**Comment by mvanbeusekom** [comment]
When using version 3.0.1 this problem should be solved.
