### ISSUE TITLE
No podspec found for `google_api_availability`

### ISSUE THREAD

**Issue by ferbeltran** [BaseflowIT/flutter-geolocator#207]
## 🐛 Bug Report

2 days ago my project started to fail, after trying to run pod install. google_apis_availability was updated to version 2.0.0 also the same day, creating a simple flutter project in macOS and adding geolocator 3.0.0 yo yaml's file crashes pod install

My pod file already has use_frameworks! and swift version set to 4.2

### Reproduction steps

1. Create a simple flutter project with: flutter create -I swift -a kotlin errortest
2. add geolocator: ^3.0.0 to yaml file
3. go to iOS folder and run: pod install

### Configuration

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-MX)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[!] Android Studio (version 3.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.31.1)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by marcuslma** [comment]
Same here!

**Comment by Kleak** [comment]
Is there some news on this ?
Just fall into this bug when releasing our app on the app store :/

**Comment by mvanbeusekom** [comment]
Should be solved with release 3.0.1 of the Geolocator plugin (which was just released).
