### ISSUE TITLE
Add GPS location listener

### ISSUE THREAD

**Issue by dark-chocolate** [BaseflowIT/flutter-geolocator#211]
## 🏗 Enhancement Proposal
It would be nice to see a location listener implemented. For instance in Android, most of the users turn on location services by swiping down the notification and the app isn't able to recognise if location services a.k.a GPS is on/off.

 Maybe this is not a good proposal as you might say this can be done using method channel as it is only related to the Android, but I just wanted to let you know if you can do that, because using method channel there will be lot of going back-forth for client. 

### Platforms affected (mark all that apply)
Android

**Comment by mvanbeusekom** [comment]
@dark-chocolate, this feature has been added to the `location_permissions` plugin which is now part of the `geolocator` plugin. 

You can get a stream informing you about changes of the location services by calling the `LocationPermissions.serviceStatus` property (for more info see: https://github.com/BaseflowIT/flutter-permission-plugins/blob/92494d4b0344e8e4fd7ca69f8e633ecb3d81f841/packages/location_permissions/lib/src/location_permissions.dart#L93)

**Comment by alvincast** [comment]
Hello @mvanbeusekom  how i can get access to LocationPermissions.serviceStatus  in the geolocator package i dont found a reference to it...

**Comment by mvanbeusekom** [comment]
Hello @alvincast, if you are using the latest version of the geolocator (6.0.0) you can use the `isLocationServiceEnabled` method as documented here (see last code example): https://github.com/Baseflow/flutter-geolocator#geolocation

**Comment by alvincast** [comment]
But i can have access to the stream? of that method?

**Comment by alvincast** [comment]
@mvanbeusekom  i need that stream to check in real time the change on gps status

**Comment by alvincast** [comment]
i mean this
 /// Allows listening to the enabled/disabled state of the location service, currently only on Android.
  ///
  /// This is basically the stream version of [checkPermissionStatus()].
  Stream<ServiceStatus> get serviceStatus {
    assert(Platform.isAndroid,
        'Listening to service state changes is only supported on Android.');

    return _eventChannel.receiveBroadcastStream().map((dynamic status) =>
        status ? ServiceStatus.enabled : ServiceStatus.disabled);
  }
