### ISSUE TITLE
App crashes if close application during await getCurrentPosition (Android)

### ISSUE THREAD

**Issue by pamir72** [BaseflowIT/flutter-geolocator#213]
## 🐛 Bug Report

**App crashes if I close application during await getCurrentPosition (Android).
It seems to have started after today's flutter upgrade**

E/AndroidRuntime( 4949): FATAL EXCEPTION: main
E/AndroidRuntime( 4949): Process: ru.ser.spm, PID: 4949
E/AndroidRuntime( 4949): java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
E/AndroidRuntime( 4949): 	at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:523)
E/AndroidRuntime( 4949): 	at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:486)
E/AndroidRuntime( 4949): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:129)
E/AndroidRuntime( 4949): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:204)
E/AndroidRuntime( 4949): 	at com.baseflow.flutter.plugin.geolocator.data.Result.success(Result.java:22)
E/AndroidRuntime( 4949): 	at com.baseflow.flutter.plugin.geolocator.tasks.LocationUpdatesUsingLocationServicesTask.reportLocationUpdate(LocationUpdatesUsingLocationServicesTask.java:108)
E/AndroidRuntime( 4949): 	at com.baseflow.flutter.plugin.geolocator.tasks.LocationUpdatesUsingLocationServicesTask.access$000(LocationUpdatesUsingLocationServicesTask.java:19)
E/AndroidRuntime( 4949): 	at com.baseflow.flutter.plugin.geolocator.tasks.LocationUpdatesUsingLocationServicesTask$1.onLocationResult(LocationUpdatesUsingLocationServicesTask.java:40)
E/AndroidRuntime( 4949): 	at com.google.android.gms.internal.location.zzau.notifyListener(Unknown Source:4)
E/AndroidRuntime( 4949): 	at com.google.android.gms.common.api.internal.ListenerHolder.notifyListenerInternal(Unknown Source:17)
E/AndroidRuntime( 4949): 	at com.google.android.gms.common.api.internal.ListenerHolder$zaa.handleMessage(Unknown Source:5)
E/AndroidRuntime( 4949): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime( 4949): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime( 4949): 	at android.app.ActivityThread.main(ActivityThread.java:6944)
E/AndroidRuntime( 4949): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4949): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/AndroidRuntime( 4949): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Lost connection to device.

----------------------
## Configuration ##

geolocator ^3.0.0

[✓] Flutter (Channel dev, v1.2.2, on Mac OS X 10.14.3 18D109, locale ru-RU)
    • Flutter version 1.2.2 at /Users/pavelmiheev/Flutter
    • Framework revision 007a415c2a (5 days ago), 2019-02-21 20:22:47 -0800
    • Engine revision f1f19bba8f
    • Dart version 2.2.0 (build 2.2.0-dev.2.1 c92d5ca288)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/pavelmiheev/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • SM G930F • ad0b1603812a66dbad • android-arm64 • Android 8.0.0 (API 26)

• No issues found!

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by pamir72** [comment]
**Additionally. Geolocator had nothing to do.
This happens if you quickly exit the application during launching**

FATAL EXCEPTION: main
E/AndroidRuntime(23688): Process: ru.serp.spm, PID: 23688
E/AndroidRuntime(23688): java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
E/AndroidRuntime(23688): at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:514)
E/AndroidRuntime(23688): at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:477)
E/AndroidRuntime(23688): at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:129)
E/AndroidRuntime(23688): at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:204)
E/AndroidRuntime(23688): at com.tekartik.sqflite.SqflitePlugin$BgResult$1.run(SqflitePlugin.java:88)
E/AndroidRuntime(23688): at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(23688): at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(23688): at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(23688): at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime(23688): at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23688): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(23688): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process (23688): Sending signal. PID: 23688 SIG: 9
Lost connection to device.

**Comment by dark-chocolate** [comment]
@pamir72 I think Geolocator is responsible for this, `reportLocationUpdate()` in `LocationUpdatesUsingLocationServicesTask` is having issue. So, I request BaseflowIT team to look into this. Thank you :)

**Comment by pamir72** [comment]
> @pamir72 I think Geolocator is responsible for this, `mEventResult.success(o);` in `Result` class is crashing, I wrapped it in `try-catch` block so it doesn't crash the app but every second my `catch` block is getting called, can anyone suggest a better solution here?

Apparently the problem is global [Cannot execute operation because FlutterJNI is not attached to native. #28651](https://github.com/flutter/flutter/issues/28651)
