### ISSUE TITLE
use google_api_availability: 2.0.0

### ISSUE THREAD

**Issue by jaumard** [BaseflowIT/flutter-geolocator#215]
Having deps in Kotlin / Swift is a nightmare ^^ nice to see you're migrating ! 
But this one is still using the old Kotlin/swift version of google_api_availability

I would appreciate if you can update it and publish a fix as I'm getting Kotlin version compilation error :( 

Thanks a lot guys !

**Comment by jaumard** [comment]
I've tried dependency_overrides to use `google_api_availability: 2.0.0` but look like the signature also change so it doesn't compile anymore. :(

**Comment by mvanbeusekom** [comment]
Solved in version 3.0.1 of the Geolocator. Thanks for the feedback.
