### ISSUE TITLE
Make `fromMap` methods public for Position and Placemark.

### ISSUE THREAD

**Issue by rhalff** [BaseflowIT/flutter-geolocator#216]
## 🏗 Enhancement Proposal

Make the following methods public:
 - `Position._()`
 -  `Position._fromMap()`
 - `Position._fromMaps()`
 - `Placemark._()`
 - `Placemark._fromMap()`
 - `Placemark._fromMaps()`

`part of` could also be removed in this case.

### Pitch

These methods are useful for mocking positions, right now there is no way to create your own Positions or Placemarks.

### Platforms affected (mark all that apply)
- [ x] :iphone: iOS
- [ x] :robot: Android

**Comment by synw** [comment]
I had the same concern and ended up making my own data structure and methods to workaround this: https://github.com/synw/geopoint

**Comment by rhalff** [comment]
@synw thanks will have a look. Perhaps there is a reason this package is so "sealed"? Personally I prefer to be able to use the types from the package itself, instead of having to write an abstraction on top of it.

Perhaps I should change my design though and not force this package to make the api public.

**Comment by rhalff** [comment]
I'm closing this again as I've modeled my own structure on top, so it doesn't have much priority for me at the moment.

**Comment by marcellus-jeanbernard** [comment]
Hello Guy 
I develop something in flutter look at the message above 

The method 'fromMap' isn't defined for the class 'Item'

anyone of you can help me
