### ISSUE TITLE
`google_api_availability` does not specify a Swift version and none of the targets 

### ISSUE THREAD

**Issue by prasant10050** [BaseflowIT/flutter-geolocator#219]
## 🐛 Bug Report
`google_api_availability` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

### Configuration

**Version:** 3.0.0

**Platform:** Both
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
Please update to version 3.0.1 of the Geolocator plugin. This takes a dependency on `google_api_availability` version 2.0.0 which is updated to use Objective-C instead of Swift. This should solve your problem.
