### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by MVelascoFlores** [BaseflowIT/flutter-geolocator#221]
### PROBLEM
This error appear when i put the dependency geolocator, if remove the package all works fine

### OUTPUT
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  Output:  /home/mvelasco/Documentos/build/app/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  /home/mvelasco/Documentos/build/app/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  /home/mvelasco/Documentos/build/app/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:965: error: resource android:attr/fontVariationSettings not found.
  /home/mvelasco/Documentos/build/app/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:966: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

**Version:** 3.0.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
Please make sure you update to version 3.0.1 and you also update the Flutter project to support AndroidX (check [here](https://github.com/BaseflowIT/flutter-geolocator/issues/196#issuecomment-465460801) for instructions)
