### ISSUE TITLE
Still use_frameworks! and config.build_settings['SWIFT_VERSION'] = '4.2' necessary???

### ISSUE THREAD

**Issue by marcuslma** [BaseflowIT/flutter-geolocator#224]
## 💬 Questions and Help

Still `use_frameworks!` and `config.build_settings['SWIFT_VERSION'] = '4.2'` necessary in version 3.0.1?
There is any incompatibility with `firebase_messaging` or `cloud_firestore`?

**Comment by mvanbeusekom** [comment]
@marcuslma yes it is still necessary, as you can see version 3.0.1 is still based on SWIFT.

We are in the progress to rewriting it into Objective-C and we target to release it with version 4.0.0

**Comment by marcuslma** [comment]
Thanks for the quick answer!
