### ISSUE TITLE
checkGeolocationPermissionStatus causes ClassCastException java.lang.String cannot be cast to java.lang.Integer

### ISSUE THREAD

**Issue by Philip-Wu** [BaseflowIT/flutter-geolocator#226]
Version: geolocator 3.0.1
Flutter Channel stable, v1.2.1
Android Studio (version 3.3)
Running on emulator

The error occurs when calling **Geolocator().checkGeolocationPermissionStatus()** in the dependency flutter-permission-handler with the following stacktrace:
`
E/MethodChannel#flutter.baseflow.com/permissions/methods(10316): Failed to handle method call
E/MethodChannel#flutter.baseflow.com/permissions/methods(10316): java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
E/MethodChannel#flutter.baseflow.com/permissions/methods(10316): 	at com.baseflow.permissionhandler.PermissionHandlerPlugin.onMethodCall(PermissionHandlerPlugin.java:186)
E/MethodChannel#flutter.baseflow.com/permissions/methods(10316): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/MethodChannel#flutter.baseflow.com/permissions/methods(10316): 	at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handleMessageFromDart(FlutterNativeView.java:188)
E/MethodChannel#flutter.baseflow.com/permissions/methods(10316): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
E/MethodChannel#flutter.baseflow.com/permissions/methods(10316): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter.baseflow.com/permissions/methods(10316): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#flutter.baseflow.com/permissions/methods(10316): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#flutter.baseflow.com/permissions/methods(10316): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#flutter.baseflow.com/permissions/methods(10316): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter.baseflow.com/permissions/methods(10316): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#flutter.baseflow.com/permissions/methods(10316): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter (10316): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, java.lang.String cannot be cast to java.lang.Integer, null)
E/flutter (10316): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter (10316): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
E/flutter (10316): <asynchronous suspension>
E/flutter (10316): #2      PermissionHandler.checkPermissionStatus (package:permission_handler/permission_handler.dart:37:48)
E/flutter (10316): <asynchronous suspension>
E/flutter (10316): #3      Geolocator.checkGeolocationPermissionStatus (package:geolocator/geolocator.dart:46:10)
E/flutter (10316): <asynchronous suspension>
`

**Comment by mvanbeusekom** [comment]
Should be fixed in version 4 and higher

**Comment by KnucklesEQ** [comment]
A note for people using Android Studio:

If someone, after upgrading the 'Geolocator' plugin and the 'Permission_handler' plugin still have the same problem, first you have to clean the project ("_flutter clean_"), and then run it again.
