### ISSUE TITLE
Location is not retrived by Geolocator on android 8.1

### ISSUE THREAD

**Issue by jkyon** [BaseflowIT/flutter-geolocator#238]
Hi guys

The geolocator is not working, it always return null, and the console display the following message:
D/permissions_handler(24003): No permissions found in manifest for: $permission
D/permissions_handler(24003): No permissions found in manifest for: $permission
I/flutter (24003): decodePermissionRequestResult called with: value:[{3: 4}]

This messages do not make any sense because I have added the permissions required:
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
<uses-permission android:name="android.permission.INTERNET" />
 
I'm not sure if I miss something in the plugin configuration

This was tested on an android 8.1 device (Nexus 6P)

Thank you in advance

**Comment by mvanbeusekom** [comment]
have you added the permissions in you AndroidManifest.xml file (see [README.md](https://github.com/BaseflowIT/flutter-geolocator/blob/develop/README.md) for details)?

**Comment by jkyon** [comment]
yes, I have added the following permisssions

<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
        <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
	    <uses-permission android:name="android.permission.INTERNET" />

However, it does not work

**Comment by jkyon** [comment]
Hi
yes, I have added the following permissions to the manifest
android.permission.ACCESS_FINE_LOCATION
android.permission.ACCESS_COARSE_LOCATION
android.permission.INTERNET

However, it does not work

thank you

**Comment by addyi** [comment]
Hi, 

I've got the same problem. And yes I also added them in the manifest bevor I compiled.

Are there any suggestions?
@jkyon Have you found a solution for your problem?

Thank you

Addyi

**Comment by bjonnycw** [comment]
I've got the same problem.
Have you found a solution for your problem?

**Comment by bjonnycw** [comment]
I believe I can solve this problem with "flutter clean" and uninstalll the app.

**Comment by DJFreh** [comment]
The solution is to delete the folder build and let it be created again by Flutter.

**Comment by samuelhk0595** [comment]
Thank you! @DJFreh
