### ISSUE TITLE
InfoWindow showed with wrong name after movecamera or animatecamera

### ISSUE THREAD

**Issue by paulobreim** [BaseflowIT/flutter-geolocator#239]
### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by paulobreim** [comment]
When you are seeing a text in the mark (registered by InfoWindow), if you use movecamera or animatecamera, to a new position, the label showed in this new position is the marke stil sow the label name from the previous place.
To fix it, just turn off the label exibition.

**Comment by mvanbeusekom** [comment]
How is this related to the `Geolocator` plugin?
