### ISSUE TITLE
Geolocator Crashes

### ISSUE THREAD

**Issue by marcglasberg** [BaseflowIT/flutter-geolocator#243]
I'm getting this using **geolocator 3.0.1** on Android.  

I'm not sure, but I believe this error happens when we try to read the location before the last reading has finished. It crashes if you try reading the position 100 times within a loop.

    E/AndroidRuntime( 8677): FATAL EXCEPTION: main
    E/AndroidRuntime( 8677): Process: test.app, PID: 8677
    E/AndroidRuntime( 8677): java.lang.IllegalStateException: Reply already submitted
    E/AndroidRuntime( 8677): 	at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl$1.reply(FlutterNativeView.java:197)
    E/AndroidRuntime( 8677): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:204)
    E/AndroidRuntime( 8677): 	at com.baseflow.flutter.plugin.geolocator.data.Result.success(Result.java:22)
    E/AndroidRuntime( 8677): 	at com.baseflow.flutter.plugin.geolocator.tasks.LocationUpdatesUsingLocationServicesTask.reportLocationUpdate(LocationUpdatesUsingLocationServicesTask.java:108)
    E/AndroidRuntime( 8677): 	at com.baseflow.flutter.plugin.geolocator.tasks.LocationUpdatesUsingLocationServicesTask.access$000(LocationUpdatesUsingLocationServicesTask.java:19)
    E/AndroidRuntime( 8677): 	at com.baseflow.flutter.plugin.geolocator.tasks.LocationUpdatesUsingLocationServicesTask$1.onLocationResult(LocationUpdatesUsingLocationServicesTask.java:40)
    E/AndroidRuntime( 8677): 	at com.google.android.gms.internal.location.zzau.notifyListener(Unknown Source:4)
    E/AndroidRuntime( 8677): 	at com.google.android.gms.common.api.internal.ListenerHolder.notifyListenerInternal(Unknown Source:17)
    E/AndroidRuntime( 8677): 	at com.google.android.gms.common.api.internal.ListenerHolder$zaa.handleMessage(Unknown Source:5)
    E/AndroidRuntime( 8677): 	at android.os.Handler.dispatchMessage(Handler.java:106)
    E/AndroidRuntime( 8677): 	at android.os.Looper.loop(Looper.java:164)
    E/AndroidRuntime( 8677): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
    E/AndroidRuntime( 8677): 	at java.lang.reflect.Method.invoke(Native Method)
    E/AndroidRuntime( 8677): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    E/AndroidRuntime( 8677): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

I'm using Flutter 1.2 stable.

**Comment by VeprUA** [comment]
This could be an implementation issue, could you please provide more detail as to how you are doing it? Is it part of some stateful/stateless widget? 

Thanks)

**Comment by marcglasberg** [comment]
Yes, sure. I have a timer:

    Timer(Duration(milliseconds: 500), () {doStuff()});

And when the callback is called, it uses the Geolocator and then starts another timer.

Note I cannot use a stream, since each time the Geolocator is called it will be different depending on some criteria. For example, sometimes I get the last known location, and sometimes I get the current position, with different accuracy settings etc.

**Comment by marcglasberg** [comment]
@VeprUA Please run this code to see the error:

    import 'dart:async';
    import 'package:flutter/material.dart';
    import 'package:geolocator/geolocator.dart';
    
    class Home extends StatefulWidget {
      @override
      _HomeState createState() => _HomeState();
    }
    
    class _HomeState extends State<Home> {
      int counter;
    
      @override
      void initState() {
        super.initState();
        counter = 0;
      }
    
      @override
      Widget build(BuildContext context) {
        return Center(
          child: RaisedButton(
            onPressed: run,
            child: Text('Run'),
          ),
        );
      }
    
      void run() {
        print('RUN.');
        Timer.periodic(Duration(milliseconds: 1), (timer) async {
          int localCounter = counter;
          print('Ask $localCounter.');
          var position = await getCurrentPositionAndTurnTimerOnAgain();
          print('Reply $localCounter => ${position?.latitude}, ${position?.longitude}');
        });
      }
    
      Future<Position> getCurrentPositionAndTurnTimerOnAgain() async {
        counter++;
        return counter % 2 == 0
            ? await Geolocator().getCurrentPosition(desiredAccuracy: LocationAccuracy.high)
            : await Geolocator().getLastKnownPosition(desiredAccuracy: LocationAccuracy.high);
      }
    }

**Comment by marcglasberg** [comment]
@VeprUA Hello! Did you manage to reproduce the bug with the above code?
