### ISSUE TITLE
GeolocationStatus is too generic

### ISSUE THREAD

**Issue by Lootwig** [BaseflowIT/flutter-geolocator#244]
The enum tries to combine two mutually non-exclusive properties: whether the app has permission to access GPS, and whether the service is enabled. However, the current values are named in a way that does not disclose both states - "disabled" does not contain any information whether access is just a matter of enabling the service or if permission has to be requested as well.

Suggestion: Either use two distinct properties and corresponding enums (the cleaner solution IMO), or include all possible constellations in the enum (probably less of a "breaking" change):

[grantedAndEnabled, grantedButDisabled, enabledButDenied, disabledAndDenied] (+ unknown... is it possible for both properties to be in unknown state?)

**Comment by mvanbeusekom** [comment]
@Lootwig we agree and released version 4.0.0 of the Geolocator app today which removes the `PermissionStatus.disabled` and allows you to check permissions even when the location services are disabled. 

If you want to make sure location services are running you can call the `isLocationServiceEnabled` method.
