### ISSUE TITLE
No permission request pop up on Android

### ISSUE THREAD

**Issue by DylandeWit** [BaseflowIT/flutter-geolocator#254]
## 🐛 Bug Report

The package doesn't ask for permission on Android. On calling `Geolocator().checkGeolocationPermissionStatus()` it immediately returns 'denied'. On iOS it works as intended. 

The [location](https://pub.dartlang.org/packages/location) does work with this pop up. With the same configuration.

### Expected behavior
The first time the permission status is checked, it should ask for permission with a pop up.

### Reproduction steps
Using `await Geolocator().checkGeolocationPermissionStatus()` on Android does not show pop up.

### Configuration
**Version:** 4.0.2

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android

**Comment by njovy** [comment]
I'm having the same issue on both platform, android and iOS.
It doesn't prompt a permission dialog. Geolocator just returns .unknown on iOS and .denied on Android.

**Comment by mvanbeusekom** [comment]
@DylandeWit, @njovy, the `checkGeolocationPermissionStatus()` method is not meant to show the popup. Its purpose is to silently check the current permissions granted. 

If you want the show the permission popup you should call one of the methods to access the current location (e.g. `getCurrentPosition()`, `getLastKnownPosition()` or `getPositionStream()`). This will automatically request permissions if needed. 

If you want more manual control you could use the methods on the `Location Permissions` plugin that comes with the `Geolocator` plugin (see the [README](https://github.com/BaseflowIT/flutter-permission-plugins/blob/develop/packages/location_permissions/README.md) for more information).

**Comment by ramioooz** [comment]
Thank you @mvanbeusekom ,
this is important though,
because sometimes we want to bring back location request-permission dialog after dismissed by user.
This should be mentioned in your plugin main READ.txt

Thank you

**Comment by diegoveloper** [comment]
+1 if this work for iOS , it should works for Android too, would be a great feature.

**Comment by mehdok** [comment]
@mvanbeusekom , The problem is this method returns wrong permission at first time, it returns `denied` which is wrong and should be `unknown`.

**Comment by jovanovski** [comment]
> @mvanbeusekom , The problem is this method returns wrong permission status at first time, it returns `denied` which is wrong and should be `unknown`.

Was this ever fixed?

**Comment by mvanbeusekom** [comment]
@jovanovski this is working as intended (according to [Android specifications](https://developer.android.com/training/permissions/requesting#perm-check)) and this will not be fixed.
