### ISSUE TITLE
Listening for permission changes

### ISSUE THREAD

**Issue by rami965** [BaseflowIT/flutter-geolocator#266]
## 💬 Questions and Help

Is there anyway to check if the location permission changed ?
I am using 

> checkGeolocationPermissionStatus()

but I get the permission status only upon calling this method. I want to listen if location services status changed.

Thanks

**Comment by mvanbeusekom** [comment]
No this is unfortunately not supported by the Android and iOS platforms and therefore also not supported by our plugin.
