### ISSUE TITLE
Option to configure distanceFilter

### ISSUE THREAD

**Issue by nicolasjon** [BaseflowIT/flutter-geolocator#27]
Great work! Good to see we can set desiredAccuracy. Please can we have an option to set DistanceFilter to "throttle" updates.

Thanks.
Nicolas

**Comment by mvanbeusekom** [comment]
Hi @nicolasjon, thanks for your feedback. I am however not 100% sure what it is you are asking here, would you mind explaining the use case a bit more detailed? 

To me it looks like you need some kind of geofencing functionality where events are only pushed on the stream returned from the `getPositionStream` when the devices enters or leaves a certain area. Is this correct or do you mean something different?

**Comment by nicolasjon** [comment]
Hi,

In one of my native iOS apps I use locationManager.distanceFilter set to
100. The location is then only updated when it has changed by 100m.
Otherwise it is updated continuously  which can be expensive if a query is
run every time it changes, and doubtless has battery and performance issues.


I have made a quick hack change to your locationservices.swift to implement
this. Of course this should really be a parameter(!)

I hope this helps.

public func startTracking(accuracy: CLLocationAccuracy) {
    if(_locationManager == nil)
    {
        _locationManager = CLLocationManager()
        _locationManager!.delegate = self

        if (CLLocationManager.authorizationStatus() == .notDetermined) {
            if (Bundle.main.object(forInfoDictionaryKey:
"NSLocationWhenInUseUsageDescription") != nil) {
                _locationManager!.requestWhenInUseAuthorization()
            }
            else if (Bundle.main.object(forInfoDictionaryKey:
"NSLocationAlwaysUsageDescription") != nil) {
                _locationManager!.requestAlwaysAuthorization();
            }
            else {
                NSException(name:
NSExceptionName.internalInconsistencyException, reason:"To use
location in iOS8 you need to define either
NSLocationWhenInUseUsageDescription or
NSLocationAlwaysUsageDescription in the app bundle's Info.plist file",
userInfo: nil).raise()
            }

        }

        _locationManager!.desiredAccuracy = accuracy;
       * _locationManager!.distanceFilter = 100;     // Hack change to
only get updates if changed by 100m*
    }

**Comment by mvanbeusekom** [comment]
@nicolasjon thanks for the feedback, sounds like an awesome feature. We will be integrating it as soon as possible (hopefully we can release it next week)
