### ISSUE TITLE
LocationPermissionLevel problems on iOS

### ISSUE THREAD

**Issue by matthewlloyd** [BaseflowIT/flutter-geolocator#271]
## 🚀 Feature Requests

The plugin currently always requests `LocationPermissionLevel.location`. The `location_permissions` plugin then requests either "when in use" or "always" permissions based on which strings are available in the app bundle. However, Apple is now rejecting binaries that could call `requestAlwaysAuthorization` but don't have the necessary strings set up, so even though `requestAlwaysAuthorization` never gets called by such an app, Apple will still reject it.

In practice this means it's now impossible to use the plugin for an app that only needs "when in use" permissions.

### Describe the feature

It should be possible to configure which `LocationPermissionLevel` the plugin will request when the first calls to `getCurrentPosition` etc. are made, perhaps by using optional named arguments to those methods.

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
@matthewlloyd you are 100% correct, we need an optional parameter here to indicate which permission level you would like to use "when in use" or "always" (default).
