### ISSUE TITLE
App crashes with /il_dbc.cc: error: unreachable code after a few seconds of location updates

### ISSUE THREAD

**Issue by rockgecko-development** [BaseflowIT/flutter-geolocator#272]
## 🐛 Bug Report

My app crashes a few seconds after I start receiving location updates. The log output is:
```
../../third_party/dart/runtime/vm/compiler/backend/il_dbc.cc: 151: error: unreachable code
version=2.3.0-dev.0.5.flutter-a1668566e5 (Tue Apr 30 20:35:41 2019 +0200) on "ios_dbc"
thread=37147, isolate=main(0x104049200)
 pc 0x0000000101617420 fp 0x00000001702c8c30 dart::Profiler::DumpStackTrace(void*)
 pc 0x0000000000000001 fp 0x00000001702c8ea0 Unknown symbol
 pc 0x0000000000000000 fp 0x00000001702c9c18 Unknown symbol
-- End of DumpStackTrace
Lost connection to device.
```

However, it doesn't crash if:

- I don't open the screen that uses location, or 
- If I have location services turned off, or
- If I run in release mode, or
- when I run my app on Android

### Reproduction steps

```dart
    var geolocator = Geolocator();
    var locationOptions =
        LocationOptions(accuracy: LocationAccuracy.best, distanceFilter: 1);

    _stream = geolocator.getPositionStream(locationOptions).listen(
        (Position currentLocation) {
      gpsEnabled = true;
      latestLocation = currentLocation;
      updateFunc(currentLocation);
    }, onError: (e) {
      print("location error: " + e.toString());
      gpsEnabled = false;
    });
```

### Configuration
iPhone 6, iOS 12

>flutter doctor:

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E227, locale
>    en-AU)
> [!] Android toolchain - develop for Android devices (Android SDK version 25.0.2)
>    ✗ Flutter requires Android SDK 28 and the Android BuildTools 28.0.3
>      To update using sdkmanager, run:
>        "/Users/build/Library/Android/sdk/tools/bin/sdkmanager"
>        "platforms;android-28" "build-tools;28.0.3"
>      or visit https://flutter.dev/setup/#android-setup for detailed
>      instructions.
>    ✗ Android license status unknown.
>      Try re-installing or updating your Android SDK Manager.
>      See https://developer.android.com/studio/#downloads or visit
>      https://flutter.dev/setup/#android-setup for detailed instructions.
> [✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
> [!] Android Studio (version 2.2)
>    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>    ✗ Dart plugin not installed; this adds Dart specific functionality.
> [✓] Connected device (1 available)
> 
> ! Doctor found issues in 2 categories.

I've ignored the Android errors because I use a different computer to build for Android.
**Version:** 5.0

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
@rockgecko-development is it possible to provide an example project that shows how to reproduce this error? 

From the current description I am missing some information that would help me reproduce this issue? Currently we are not able to reproduce the error and since the code example doesn't compile there is room for interpretation on our side on how your code is structured. The main problems are:

1. What happens with the `latestLocation` variable (in the example code it is set but not declared nor used);
2. Since the implementation of the `updateFunc` is missing I cannot exclude that the problem is part of this function.

**Comment by rockgecko-development** [comment]
Thanks for your help. It turned out the problem was occuring when I was formatting the lat/long coordinates for display via `NumberFormat`, and some very specific interplay between that and array methods in the Flutter framework. I filed a bug with them here: https://github.com/flutter/flutter/issues/33751

**Comment by mvanbeusekom** [comment]
@rockgecko-development thank you for updating, hopefully the bug will be picked up quickly by the Flutter team.
