### ISSUE TITLE
The use of Swift 3 @objc inference in Swift 4 mode is deprecated.

### ISSUE THREAD

**Issue by nicolasjon** [BaseflowIT/flutter-geolocator#28]
### Steps to reproduce :scroll:

When compiling for iOS release 

### Expected behaviour :thinking:

Clean build.

### Actual behaviour :warning:

The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target.

Thanks

**Comment by mvanbeusekom** [comment]
Hi @nicolasjon, thanks for reaching out, your feedback is very appreciated.

I am trying to reproduce this issue but am unfortunately failing to do so. Based on your description I am taking the following steps:

- Clone the repo: `git clone https://github.com/baseflowit/flutter-geolocator`;
- On the terminal change into the `example` folder;
- Build the iOS version (in release mode): `flutter build ios --release`

Doing so results in the following output:

```
Building com.baseflow.geolocatorExample for device (ios-release)...
Signing iOS app for device deployment using developer identity: "iPhone Developer: Maurits Beusekom (SUMZR2RT3D)"
Starting Xcode build...
 ├─Building Dart code...                              1.8s
 ├─Assembling Flutter resources...                    1.0s
 └─Compiling, linking and signing...                  4.6s
Xcode build done.                                            8.3s
```

There is no mention of the error or warning you described above. Could you please elaborate?

**Comment by nicolasjon** [comment]
Hi,

I am using the package from another  project, I will try building the
release version from your package

Nicolas

**Comment by nicolasjon** [comment]
Hi,

Building com.baseflow.geolocatorExample for device (ios-release)...

Automatically signing iOS for device deployment using specified development
team in Xcode project: LK5496HQGV

Running pod install...                                       1.2s

Starting Xcode build...

 ├─Building Dart code...                             22.1s

 ├─Assembling Flutter resources...                    1.2s

 └─Compiling, linking and signing...                 18.7s

Xcode build done.                                           46.7s

You have a faster machine than mine...

Then when I go to Archive the project I get the attached screenshot

This is the same warning as I get when building the archive for a project
that uses the location package in the standard way - i.e with pubspec.yaml
etc.

Nicolas
