### ISSUE TITLE
GPS status updates and logging on screen off

### ISSUE THREAD

**Issue by moovida** [BaseflowIT/flutter-geolocator#286]
## Questions

Hi, thanks for this amazing plugin! I have 2 questions:

* Is there a way to get GPS status updates? Like GPS turned on and off, getting and losing fix?
* is there a way to continue logging also with the device screen off? On newer Android devices it quite limited and requires some tweaking. I am testing the logging of a line on the map and everytime I turn the screen on, the GPS stops and when i turn it on, the current position is updated at once, connecting the positions with a straight line.

Thanks for any help!

**Comment by moovida** [comment]
I apologize, I just noticed that point 2 is handled in issue #53 .
Will add my appreciation there :-)

**Comment by mvanbeusekom** [comment]
@moovida to my knowledge this is not supported by the default mobile platforms. The only updates we can (and do) provide is if the location services are being turned on or off. 

Information regarding GPS status are not provided by the SDKs supplied by Apple and Google so we have no (official) way to get this information unfortunately.
