### ISSUE TITLE
Build failed with an exception.

### ISSUE THREAD

**Issue by mukhtarhussainbaloch** [BaseflowIT/flutter-geolocator#292]
## 🐛 Bug Report

FAILURE: Build failed with an exception.

* What went wrong:
Failed to notify build completion listener.
> com.android.tools.lint.LintCoreApplicationEnvironment

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Finished with error: Gradle task assembleDebug failed with exit code 1
### Configuration

**Version:** 1.0.5

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.18362.175], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Android Studio (version 3.4)
[√] VS Code (version 1.35.1)
[√] Connected device (1 available)

• No issues found!

The Project is migrated to AndroidX. It also works on Android without the geolocator plugin.

**Comment by mvanbeusekom** [comment]
Don't see how this affect the Geolocator plugin. The exception points to something related to your environment.

Did you upgrade to AndroidX (see comments in [README.md](https://github.com/BaseflowIT/flutter-geolocator/blob/develop/README.md))?
