### ISSUE TITLE
Geocoding address has hardcoded max results count 1 on Android

### ISSUE THREAD

**Issue by audkar** [BaseflowIT/flutter-geolocator#293]
## 🐛 Bug Report

Max returned results count is always `<= 1` while goecoding from address. [Related code](https://github.com/BaseflowIT/flutter-geolocator/blob/master/android/src/main/java/com/baseflow/geolocator/tasks/ForwardGeocodingTask.java#L44). 

Is this done on purpose or a bug?

### Expected behavior

Return all results or have parameter for a limit.

### Configuration

**Version:** 5.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
This is a bug, would be great if you could provide a PR with a fix for this.

**Comment by audkar** [comment]
From my testing Android geocoder always return max results of 1. So that might not be an accident :)

Created PR to increase limit for android just to align android behavior with iOS in case more result would be found.
