### ISSUE TITLE
After Permission granted 

### ISSUE THREAD

**Issue by kingkhan7511** [BaseflowIT/flutter-geolocator#296]
Create a call back after permission granted/denied from ios and both ?

**Comment by mvanbeusekom** [comment]
@kingkhan7511 internally the Geolocator plugin uses the `location_permissions` plugin to take care of permissions. If you want a bit more control you can directly refer to the plugin yourself and handle permissions.

More info can be found here: https://github.com/BaseflowIT/flutter-permission-plugins/tree/develop/packages/location_permissions
