### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by OsamaMaani** [BaseflowIT/flutter-geolocator#298]
## 🐛 Bug Report

###*these lines of codes appears whenever I try to run the project : 
Could not resolve all files for configuration ':geolocator:lintClassPath'.
> Could not download lint.jar (com.android.tools.lint:lint:26.3.0)
   > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint/26.3.0/lint-26.3.0.jar'.
      > Read timed out
> Could not download lint-api.jar (com.android.tools.lint:lint-api:26.3.0)
   > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-api/26.3.0/lint-api-26.3.0.jar'.
      > Read timed out
> Could not download intellij-core.jar (com.android.tools.external.com-intellij:intellij-core:26.3.0)
   > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/intellij-core/26.3.0/intellij-core-26.3.0.jar'.
      > Read timed out
> Could not download kotlin-compiler.jar (com.android.tools.external.com-intellij:kotlin-compiler:26.3.0)
   > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/kotlin-compiler/26.3.0/kotlin-compiler-26.3.0.jar'.
      > Read timed out
> Could not download uast.jar (com.android.tools.external.org-jetbrains:uast:26.3.0)
   > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/external/org-jetbrains/uast/26.3.0/uast-26.3.0.jar'.
      > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/external/org-jetbrains/uast/26.3.0/uast-26.3.0.jar'.
         > Connect to dl.google.com:443 [dl.google.com/216.58.198.78] failed: Connection timed out: connect
> Could not download groovy-all.jar (org.codehaus.groovy:groovy-all:2.4.15)
   > Could not get resource 'https://jcenter.bintray.com/org/codehaus/groovy/groovy-all/2.4.15/groovy-all-2.4.15.jar'.
      > Could not GET 'https://jcenter.bintray.com/org/codehaus/groovy/groovy-all/2.4.15/groovy-all-2.4.15.jar'.
         > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/35.158.148.134, jcenter.bintray.com/18.184.128.152] failed: Connection timed out: connect
> Could not download trove4j.jar (org.jetbrains.trove4j:trove4j:20160824)
   > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/trove4j/trove4j/20160824/trove4j-20160824.jar'.
      > Could not GET 'https://jcenter.bintray.com/org/jetbrains/trove4j/trove4j/20160824/trove4j-20160824.jar'.
         > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/35.158.148.134, jcenter.bintray.com/18.184.128.152] failed: Connection timed out: connect
> Could not download error_prone_annotations.jar (com.google.errorprone:error_prone_annotations:2.1.3)
   > Could not get resource 'https://jcenter.bintray.com/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar'.
      > Could not GET 'https://jcenter.bintray.com/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar'.
         > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/35.158.148.134, jcenter.bintray.com/18.184.128.152] failed: Connection timed out: connect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 53s
Finished with error: Gradle task assembleDebug failed with exit code 1
 

### Reproduction steps

**Version:** 5.0.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by lightblueUSA** [comment]
I fixed the issues using that answer from stackoverflow 
https://stackoverflow.com/questions/50747483/flutter-build-failed-with-an-exception-for-geolocation-plugin/50747662     :D

**Comment by sjoerd0301** [comment]
Hi!

Could you post what exactly what you did, for future reference?
Thanks!

**Comment by MangeshKadam** [comment]
In your app's top level build.gradle update classpath. For me 
classpath 'com.android.tools.build:gradle:3.5.3' is working fine.
