### ISSUE TITLE
meta update in 5.1.1. fails on flutter get packages

### ISSUE THREAD

**Issue by nicodewet** [BaseflowIT/flutter-geolocator#302]
## 🔙 Regression

With a vanilla Flutter 1.7.8+hotfix.3 generated project ($flutter create geo_test)...

### Old (and correct) behavior

If you add 5.1.0 as a dependency I get, in VS Code:

[geo_test] flutter packages get
Running "flutter pub get" in geo_test...                            5.2s
exit code 0

### Current behavior

If you add 5.1..1 as a dependency I get, in VS Code:

Running "flutter pub get" in geo_test...                        
Because every version of flutter_test from sdk depends on meta 1.1.6 and geolocator >=5.1.1 depends on meta ^1.1.7, flutter_test from sdk is incompatible with geolocator >=5.1.1.
So, because geo_test depends on both geolocator ^5.1.1 and flutter_test any from sdk, version solving failed.

pub get failed (1)
exit code 1

### Reproduction steps

Already described above.

**Comment by mvanbeusekom** [comment]
Thanks for the issue, we quickly supplied an update to fix this issue (version: 5.1.1+1).
