### ISSUE TITLE
Support Android 10s background location permission

### ISSUE THREAD

**Issue by athornz** [BaseflowIT/flutter-geolocator#322]
## 🚀 Feature Requests

Support Android 10s background location permission

This will be automatically supported once this PR is merged: https://github.com/BaseflowIT/flutter-permission-plugins/pull/16

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [X] :robot: Android

**Comment by mvanbeusekom** [comment]
Solved in release 5.1.4. Thanks for contributing.
