### ISSUE TITLE
Does it supports iOS significant location update?

### ISSUE THREAD

**Issue by LaemonT** [BaseflowIT/flutter-geolocator#329]
Hi, does this package supports iOS significant location update?

**Comment by StijnWoerkom** [comment]
@LaemonT The flutter-geolocator has the purpose of providing continuously the location of the user.  The iOS significant location update package is against the purpose of the geolocator. On the iOS version is CLLocationManager supported for the managing of location updating. 

Short briefing: No, it is not supported.

**Comment by LaemonT** [comment]
> @LaemonT The flutter-geolocator has the purpose of providing continuously the location of the user. The iOS significant location update package is against the purpose of the geolocator. On the iOS version is CLLocationManager supported for the managing of location updating.
> 
> Short briefing: No, it is not supported.

Okay, thanks for your replay 😃
