### ISSUE TITLE
Issue with grpc failed. 

### ISSUE THREAD

**Issue by sokolej79** [BaseflowIT/flutter-geolocator#339]
## 🐛 Bug Report

When turning off the network and turning it on again, it almost always shows this error. 
Version ^5.1.4+1. 

### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by StijnWoerkom** [comment]
Could you provide me with some more details? What is the exact error you are getting?
