### ISSUE TITLE
Missing course (heading) information on iOS. (Again :-/)

### ISSUE THREAD

**Issue by SirJohn2024** [BaseflowIT/flutter-geolocator#340]
Version [5.1.4] states:

- Return heading as part of the position on iOS.

But the fix has not been ported to the actual version, still broken...

`             @"speed_accuracy": @(self.course),`    !????

**Comment by mvanbeusekom** [comment]
@SirJohn2024 I see the mistake now, we will fix it asap in version 5.1.4+2

**Comment by mvanbeusekom** [comment]
@SirJohn2024 this should be fixed now, thank you for helping out.
