### ISSUE TITLE
Issues with Pixel XL Emulator (API 25)

### ISSUE THREAD

**Issue by lielfr** [BaseflowIT/flutter-geolocator#341]
### Reproduction steps
Start with a new flutter app, add Geolocator (with all the appropriate settings) and add this code: 
`Position position = await Geolocator().getCurrentPosition(desiredAccuracy: LocationAccuracy.low);`
`print(position);`
The position is not reported.

### Configuration

**Version:** 5.1.4+1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by lielfr** [comment]
Well, this seems to be an issue with native android apps as well.

**Comment by StijnWoerkom** [comment]
@lielfr What behavior do you expect? I executed your reproduction steps and got a location on a Pixel XL Emulator (API 25).

**Comment by lielfr** [comment]
I just expect it to be printed. For some reason, it seemingly doesn't work on my emulator, as well as a friend's emulator. Using a high accuracy or forcing Geolocator to use LocationManager seems to work however

**Comment by StijnWoerkom** [comment]
It just depends on what you need at the moment. We provided a demo app that provides a button that prints your location forcing LocationManger. You can use that to print your location.

**Comment by lielfr** [comment]
Yup, it works. Seemingly it is a local problem or at least a problem with the fused location API, but thanks a lot :smile:
