### ISSUE TITLE
PositionStream won't notify when the Location service stops sending current position

### ISSUE THREAD

**Issue by argamanza** [BaseflowIT/flutter-geolocator#43]
### Steps to reproduce :scroll:

1. Build basic app containing a `PositionStream` subscription[ like the example in the package's page on pub.dartlang.org](https://pub.dartlang.org/packages/geolocator#-example-tab-).

2. Run the app while **Location services are on** and permitted.

3. **Turn off Location** (or alternatively revoke permissions) while the app is running.

4. Wait a few seconds/minutes

5. **Turn Location back on** (or enable permissions)

### Expected behavior :thinking:
I should get some indication that the _Position stopped_ streaming once the Location is off, and when it turns back on the Position should start streaming again on its own.

### Actual behavior :bug:
The Position stream works well and i get the Position updates as expected, when i **turn Location off** _the last Position will stay_ until i manually request a new one using the `getPosition` method, only then i will get a `null` Position.

That way if someone had a working location but lost it for any reason there's no way to notify him, and the last position will stay "forever".

In the GIF below you can see this behavior, i'm iterating a GPX file and when i turn off Location there is no indication for that anywhere, until i press the "Refresh" button that has the following code:
```
void initPlatformState() async {
    Position position;
     try {
      position = await _geolocator.getPosition(LocationAccuracy.high);
    } on PlatformException catch (e) {
      print(e.message);
      position = null;
    }

    if (!mounted) return;

    setState(() {
      _position = position;

      if (_position == null) {
        print('NO LOCATION!');
      }
    });
  }
```

![demo](https://user-images.githubusercontent.com/9576019/42663352-d67d3fd2-863d-11e8-9bdd-270767996174.gif)

Is there something i'm doing wrong or that's a flutter's framework constraint?

### Configuration :wrench:

**Version:** 1.2.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
@argamanza thank you very much for your feedback. 

The problem here is that the stream responds to location updates triggered by the platform (Android in your case). As soon as you revoke the permissions, Android will no longer submit any location updates and thus the stream will never be triggered. If I remember correctly there are ways to catch permission state events which I will look into and see if this offers an opportunity to let the client App know the stream has stopped (or paused). I will get back on this soon.

**Comment by mvanbeusekom** [comment]
@argamanza the fix was relatively easy, thank you for pointing out the issue. We released a new version of the plugin (1.2.2) including the fix.

**Comment by argamanza** [comment]
Thanks!
Works great now, just another use case i found after testing just about any possible use case:
If the user enters the app while his **Location** is **off**, no matter how many times he will activate/deactivate it - the `PositionStream` won't start streaming until he reopens the app or alternatively the developer creates a special method which involves natively check the **Location Services** status and restarts the app to run the `InitState` again.

Once again, i'm pretty novice and i think a simple solution which involves timed checks for the Location status will be enough to solve this, and i don't want to start another issue for a bug which might be solved without changing the package itself.

**Comment by mvanbeusekom** [comment]
@argamanza thx again for your feedback. I think a good feature would be to make an API available where the App developer can request the current permission status. This way it would be easy for developers to check the current location status without having to implement platform specific code and can act accordingly.

Would this sound like a solution to you?

**Comment by argamanza** [comment]
@mvanbeusekom sounds great.
Getting the location permission status and rather it's on or off implemented in this package could save a lot of hassle and the need to use other packages or checking natively.

**Comment by martijn00** [comment]
@argamanza can you open a new issue for the permissions?

**Comment by JustChris** [comment]
This doesn’t seem to work. When my app is running with location service enabled and access granted and I turn off location service via Android notification drawer, I won’t get notified at all. Am I doing something wrong?
I tried it via stream provider and consumer as well as streambuilder
