### ISSUE TITLE
Add support for  kCLLocationAccuracyBestForNavigation

### ISSUE THREAD

**Issue by diegoveloper** [BaseflowIT/flutter-geolocator#48]
Could you add support for 
kCLLocationAccuracyBestForNavigation in iOS? 

Thanks

**Comment by mvanbeusekom** [comment]
@diegoveloper, we left it out because it didn't map directly to a Android specific accuracy. However we will include it and map it on Android to the `best` accuracy.

Thanks for your feedback, we will release a new update today ;)

**Comment by diegoveloper** [comment]
Awesome thankss
