### ISSUE TITLE
Location not found on Android

### ISSUE THREAD

**Issue by Asoseil** [BaseflowIT/flutter-geolocator#52]
On Android, I am able to find only the last location in memory. If I don't use Google maps or similar to find the coordinates, geolocator return a generic error "Location not found"

**Comment by Asoseil** [comment]
maybe could be useful and related https://stackoverflow.com/questions/35456254/application-getting-wrong-location-until-open-inbuilt-google-map-application

**Comment by mvanbeusekom** [comment]
@Asoseil, Thank you for very much for your feedback. This is indeed a valid observation. On Android we use call the native `getLastKnownLocation` method which indeed returns the last available (cached) location. Of course this is not what the API method (`currentLocation`) suggests so this is something we will look into and fix in our next release (hopefully this will be at the end of next week, depending a bit on availability during the holidays).

**Comment by mvanbeusekom** [comment]
@Asoseil, as a work around you could listen to the position stream and cancel the subscription as soon as you receive the first location (make sure you use the default `LocationOptions`).
