### ISSUE TITLE
error after update 

### ISSUE THREAD

**Issue by sudipta213** [BaseflowIT/flutter-geolocator#60]
Unable to find source java class: '/home/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-1.3.0/android/src/main/java/com/baseflow/flutter/plugin/geolocator/tasks/OneTimeLocationTask.java' because it does not belong to any of the source dirs: '[/home/hitanshu/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-1.4.0/android/src/main/java, /home/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-1.4.0/android/src/debug/java, /home/AndroidStudioProjects/onlinecitydemo/build/geolocator/generated/source/r/debug, /home/AndroidStudioProjects/onlinecitydemo/build/geolocator/generated/source/buildConfig/debug, /home/AndroidStudioProjects/onlinecitydemo/build/geolocator/generated/source/aidl/debug, /homeAndroidStudioProjects/onlinecitydemo/build/geolocator/generated/source/rs/debug]'
error after update

**Comment by mvanbeusekom** [comment]
@sudipta213 if I understand correctly you use the Geolocator plugin in you project and updated from version 1.3.0 to version 1.4.0, after which you suddenly started receiving this error.

You don't give a lot of helpful information, like is it a compile- or runtime-error, but it looks like your project is still keeping some old cache around. Please try running `flutter clean` before compiling again:

```
flutter clean
flutter build apk
```
