### ISSUE TITLE
Null exception from getLastKnownPosition

### ISSUE THREAD

**Issue by kaetemi** [BaseflowIT/flutter-geolocator#62]
in geolocator.dart ln 61:
```
return Position?._fromMap(position);
```
Throws an exception when position is null:

```
NoSuchMethodError: The method 'containsKey' was called on null.
```

It should instead simply return null if position is null as the documentation specifies.

**Comment by mvanbeusekom** [comment]
@kaetemi thanks for reporting this issue. Due to a holiday I was not able to respond sooner, however I have created a pull-request (#64) to solve this issue and will be released in our next update (version 1.4.1).
