### ISSUE TITLE
Android - Appears slow to report first location.

### ISSUE THREAD

**Issue by nicolasjon** [BaseflowIT/flutter-geolocator#68]
## 🐛 Bug Report

Android - Appears slow to report first location, compared to a native Android app. It does not appear to use the Android fused location provider? I have not tested getlastknown I only using get current and also registering for updates. 
On Apple a location is return instantly. 

### Expected 
My native Java apps using the fused location provider will generally return a location (of some sort) almost instantly. 

### Reproduction steps
Followed example code. Seems particularly slow if no wifi/cell connection available and it has to rely on GPS. Have had some reports of no location being returned at all

### Configuration

**Version:** 
Latest version of geoLocator

**Platform:** 
- [ ] :iphone: iOS
- [x ] :robot: Android

**Comment by nicolasjon** [comment]
Using  _geoLocator.getLastKnownPosition() returns a position almost instantly - as expected.   
```
void _initLastKnown() async {
    Position position;
    // Platform messages may fail, so we use a try/catch PlatformException.
    print("getLastKnownPosition called");
    try {
      position = await  _geoLocator.getLastKnownPosition();
    } on PlatformException {
      position = null;
    }
```

**Comment by mvanbeusekom** [comment]
@nicolasjon thanks for the feedback. On Android we are currently using the `LocationManager` instead of the `FusedLocationProviderClient`. 

To get the current location we actually have to spin up one of the location providers and get an actual fix on the devices position. Depending on the availability and desired accuracy this indeed may take some time (sometimes getting a good signal on the GPS sattelites takes some time). As you already mentioned you could use the `getLastKnownLocation` method to get an initial "fast" result and in the meantime wait for `getCurrentLocation` to get a more precise result.

Also we will be looking to add support for the `FusedLocationProviderClient` and use the `LocationManager` as fallback in cases where de `FusedLocationProviderClient` is not supported.

**Comment by nicolasjon** [comment]
Hi,

Thanks for you quick reply.
Completely agree regarding the fused location manager. I moved over to it
years ago and it has always worked way better than location manager - which
I only use as a fallback for abandoned API levels and Amazon devices
"Argh!!!". My code attempts to check for an older version of play services,
and load one if necessary.
I only require an old version of Google Play Services, in the hope that
most devices will have it or a more recent one! and thus avoid the slightly
fraught process of updating play services - when if it goes wrong - takes
ages etc... My app will be blamed! Therefore, perhaps just require an older
version of play services and as you say fall back to location manager if it
can't be found. Perhaps advising the use on the way.

I have now moved onto the latest 1.5 version and have an observation
When an app is first installed if getLastLocation is called, then position
stream setup  - The permissions dialog appears, which is fine, but an error
has already occurred. (I know this one has been discussed)

W/Activity(20556): Can reqeust only one set of permissions at a time
E/MethodChannel#flutter.baseflow.com/permissions/methods(20556): Failed to
handle method call
E/MethodChannel#flutter.baseflow.com/permissions/methods(20556):
java.lang.IllegalStateException: Reply already submitted
E/MethodChannel#flutter.baseflow.com/permissions/methods(20556): at
io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:175)
E/MethodChannel#flutter.baseflow.com/permissions/methods(20556): at
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:194)
E/MethodChannel#flutter.baseflow.com/permissions/methods(20556): at
com.baseflow.permissionhandler.PermissionHandlerPlugin.processResult(PermissionHandlerPlugin.kt:271)
E/MethodChannel#flutter.baseflow.com/permissions/methods(20556): at
com.baseflow.permissionhandler.PermissionHandlerPlugin.handlePermissionsRequest(PermissionHandlerPlugin.kt:263)
E/MethodChannel#flutter.baseflow.com/permissions/methods(20556): at
com.baseflow.permissionhandler.PermissionHandlerPlugin.access$handlePermissionsRequest(PermissionHandlerPlugin.kt:22)
E/MethodChannel#flutter.baseflow.com/permissions/methods(20556): at
com.baseflow.permissionhandler.PermissionHandlerPlugin$Companion$registerWith$1.onRequestPermissionsResult(PermissionHandlerPlugin.kt:40)
E/MethodChannel#flutter.baseflow.com/permissions/methods(20556): at
io.flutter.app.FlutterPluginRegistry.onRequestPermissionsResult(FlutterPluginRegistry.java:191)
E/MethodChannel#flutter.baseflow.com/permissions/methods(20556): at
io.flutter.app.FlutterActivityDelegate.onRequestPermissionsResult(FlutterActivityDelegate.java:125)
E/MethodChannel#flutter.baseflow.com/permissions/methods(20556): at
io.flutter.app.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:133)
E/MethodChannel#flutter.baseflow.com/permissions/methods(20556): at
android.app.Activity.requestPermissions(Activity.java:4163)
E/MethodChannel#flutter.baseflow.com/permissions/methods(20556): at
android.support.v4.app.ActivityCompat.requestPermissions(ActivityCompat.java:507)
E/MethodChannel#flutter.baseflow.com/permissions/methods(20556): at
com.baseflow.permissionhandler.PermissionHandlerPlugin.requestPermissions(PermissionHandlerPlugin.kt:224)
E/MethodChannel#flutter.baseflow.com/permissions/methods(20556): at
com.baseflow.permissionhandler.PermissionHandlerPlugin.onMethodCall(PermissionHandlerPlugin.kt:109)
E/MethodChannel#flutter.baseflow.com/permissions/methods(20556): at
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#flutter.baseflow.com/permissions/methods(20556): at
io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:164)
E/MethodChannel#flutter.baseflow.com/permissions/methods(20556): at
android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter.baseflow.com/permissions/methods(20556): at
android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#flutter.baseflow.com/permissions/methods(20556): at
android.os.Looper.loop(Looper.java:143)
E/MethodChannel#flutter.baseflow.com/permissions/methods(20556): at
android.app.ActivityThread.main(ActivityThread.java:7225)
E/MethodChannel#flutter.baseflow.com/permissions/methods(20556): at
java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter.baseflow.com/permissions/methods(20556): at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
E/MethodChannel#flutter.baseflow.com/permissions/methods(20556): at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
E/FlutterNativeView(20556): Uncaught exception in binary message listener
E/FlutterNativeView(20556): java.lang.IllegalStateException: Reply already
submitted
E/FlutterNativeView(20556): at
io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:175)
E/FlutterNativeView(20556): at
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:209)
E/FlutterNativeView(20556): at
io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:164)
E/FlutterNativeView(20556): at
android.os.MessageQueue.nativePollOnce(Native Method)
E/FlutterNativeView(20556): at
android.os.MessageQueue.next(MessageQueue.java:323)
E/FlutterNativeView(20556): at android.os.Looper.loop(Looper.java:143)
E/FlutterNativeView(20556): at
android.app.ActivityThread.main(ActivityThread.java:7225)
E/FlutterNativeView(20556): at java.lang.reflect.Method.invoke(Native
Method)
E/FlutterNativeView(20556): at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
E/FlutterNativeView(20556): at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
D/libGLESv1(20556): DTS_GLAPI : DTS is not allowed for Package :
com.zbm2.sotabeta
V/ActivityThread(20556): updateVisibility : ActivityRecord{8afbcec
token=android.os.BinderProxy@e39dd24
{com.zbm2.sotabeta/com.zbm2.fluttersotafindernew.MainActivity}} show : true


If this is location permission is accepted and then a crash occurs.


E/FlutterNativeView(20556): Uncaught exception in binary message listener
E/FlutterNativeView(20556): java.lang.IllegalStateException: Reply already
submitted
E/FlutterNativeView(20556): at
io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:175)
E/FlutterNativeView(20556): at
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:209)
E/FlutterNativeView(20556): at
io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:164)
E/FlutterNativeView(20556): at
android.os.MessageQueue.nativePollOnce(Native Method)
E/FlutterNativeView(20556): at
android.os.MessageQueue.next(MessageQueue.java:323)
E/FlutterNativeView(20556): at android.os.Looper.loop(Looper.java:143)
E/FlutterNativeView(20556): at
android.app.ActivityThread.main(ActivityThread.java:7225)
E/FlutterNativeView(20556): at java.lang.reflect.Method.invoke(Native
Method)
E/FlutterNativeView(20556): at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
E/FlutterNativeView(20556): at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
D/libGLESv1(20556): DTS_GLAPI : DTS is not allowed for Package :
com.zbm2.sotabeta
V/ActivityThread(20556): updateVisibility : ActivityRecord{8afbcec
token=android.os.BinderProxy@e39dd24
{com.zbm2.sotabeta/com.zbm2.fluttersotafindernew.MainActivity}} show : true
D/AndroidRuntime(20556): Shutting down VM
E/AndroidRuntime(20556): FATAL EXCEPTION: main
E/AndroidRuntime(20556): Process: com.zbm2.sotabeta, PID: 20556
E/AndroidRuntime(20556): java.lang.RuntimeException: Failure delivering
result ResultInfo{who=@android:requestPermissions:, request=25, result=-1,
data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has
extras) }} to activity
{com.zbm2.sotabeta/com.zbm2.fluttersotafindernew.MainActivity}:
java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(20556): at
android.app.ActivityThread.deliverResults(ActivityThread.java:4921)
E/AndroidRuntime(20556): at
android.app.ActivityThread.handleSendResult(ActivityThread.java:4964)
E/AndroidRuntime(20556): at
android.app.ActivityThread.access$1600(ActivityThread.java:221)
E/AndroidRuntime(20556): at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1848)
E/AndroidRuntime(20556): at
android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(20556): at android.os.Looper.loop(Looper.java:158)
E/AndroidRuntime(20556): at
android.app.ActivityThread.main(ActivityThread.java:7225)
E/AndroidRuntime(20556): at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20556): at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
E/AndroidRuntime(20556): at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
E/AndroidRuntime(20556): Caused by: java.lang.IllegalStateException: Reply
already submitted
E/AndroidRuntime(20556): at
io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:175)
E/AndroidRuntime(20556): at
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:194)
E/AndroidRuntime(20556): at
com.baseflow.permissionhandler.PermissionHandlerPlugin.processResult(PermissionHandlerPlugin.kt:271)
E/AndroidRuntime(20556): at
com.baseflow.permissionhandler.PermissionHandlerPlugin.handlePermissionsRequest(PermissionHandlerPlugin.kt:263)
E/AndroidRuntime(20556): at
com.baseflow.permissionhandler.PermissionHandlerPlugin.access$handlePermissionsRequest(PermissionHandlerPlugin.kt:22)
E/AndroidRuntime(20556): at
com.baseflow.permissionhandler.PermissionHandlerPlugin$Companion$registerWith$1.onRequestPermissionsResult(PermissionHandlerPlugin.kt:40)
E/AndroidRuntime(20556): at
io.flutter.app.FlutterPluginRegistry.onRequestPermissionsResult(FlutterPluginRegistry.java:191)
E/AndroidRuntime(20556): at
io.flutter.app.FlutterActivityDelegate.onRequestPermissionsResult(FlutterActivityDelegate.java:125)
E/AndroidRuntime(20556): at
io.flutter.app.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:133)
E/AndroidRuntime(20556): at
android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7263)
E/AndroidRuntime(20556): at
android.app.Activity.dispatchActivityResult(Activity.java:7141)
E/AndroidRuntime(20556): at
android.app.ActivityThread.deliverResults(ActivityThread.java:4917)
E/AndroidRuntime(20556): ... 9 more

I wish to use Lastknown as the stream position can take ages. Although now
I am unsure as to how to do this correctly/safely

Cheers
Nicolas

**Comment by mvanbeusekom** [comment]
@nicolasjon, do you await the response of the `getLastKnownPosition` method before you call the `getPositionStream` method to setup the stream?

Both methods will try to check for permissions, if not awaiting them before calling the other this can indeed go wrong. If you need a bit more control, you can also take care of the permissions yourself using our new `permission_handler` plugin. You could use this plugin to make sure all permissions are in place and after that call the `getLastKnownPosition` and `getPositionStream` methods without having to await them before continuing (since permissions are already taken care of). 

I will have a look if there is a way I can check if the app is already trying to access the Activity to request permissions and wait for that result before continuing.

**Comment by nicolasjon** [comment]
Thanks for your considered reply.

> On 15 Aug 2018, at 16:49, Maurits van Beusekom <notifications@github.com> wrote:
> 
> @nicolasjon, do you await the response of the getLastKnownPosition method before you call the getPositionStream method to setup the stream?
> 
Ah.. Both are called from separate methods... so will potentially be running together, had not thought of this, Thanks! Will change and ensure both calls are consecutive awaits in ONE async method. Thanks for the nudge on that!

I will further review the example code, as currently in my code I have an odd issue where if the device is set to GPS only, it works, but if the device is set to high accuracy (use gps, wifi etc) then no streamed location is ever received.
