### ISSUE TITLE
Customizing Location Request Alert Timing

### ISSUE THREAD

**Issue by deffs** [BaseflowIT/flutter-geolocator#77]
## 🚀 Feature Requests

Can the plugin be changed so that the location sharing request occurs when the user confirms location sharing through a button tap, for example, rather than requesting location sharing as soon as the app starts?

### Contextualize the feature

Basic Permission requesting - makes it more likely that the user will accept location sharing since they are asked before the alert appears.

### Describe the feature

Usually a button or some other interaction will cause an alert to appear with location sharing requested. Allow the user to accept location sharing with the tap of a button. 

### Platforms affected (mark all that apply)
- [X] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
@deffs I am not sure I understand here. The plug-in will not ask for permissions until one of the methods that require permissions to be there (`getLastKnownPosition`, `getCurrentPosition` or `getPositionStream`) are called.

In case of the example app, the first screen immediately calls the `getCurrentPosition` method to be able to show the current coordinates and thus it will immediately ask the user for permissions. This is how the example app is designed. 

I just made an simple test and changed the example App to show the second tab when it opens (which shows the results of the `getPositionStream` method). On this page the `getPositionStream` method is called after you press the "Start listening" button. In this case you will not be asked for permissions until you click the button or switch to the "singleLocation" tab.

If you prefer more control over the permissions you could use the `permission_handler` plug-in. This will allow you to request permissions without having to call one of the above mentioned methods. This could for example be useful in situations where you want the user to give consent during an onboarding process.

**Comment by mvanbeusekom** [comment]
@deffs I am going to close this issue now, due to inactivity. If you feel it is not correct please feel free to reopen the issue and supply the earlier requested information.

**Comment by deffs** [comment]
You are correct - I wasn't testing the plugin correctly in my code.

Thanks for the additional info.
