### ISSUE TITLE
NPE when using geolocator with android_alarm_manager

### ISSUE THREAD

**Issue by sestegra** [BaseflowIT/flutter-geolocator#82]
## 🐛 Bug Report

When using android_alarm_manager example plus geolocator plugin (see code below), I got following exception.

``` dart
void printHelloMessage(String msg) {
    Geolocator().getLastKnownPosition(LocationAccuracy.high).then((position) {
      print(new HelloMessage(
        new DateTime.now(),
        msg,
        Isolate.current.hashCode,
        null,
        position.toString(),
      ));
    });
}
```

```
E/MethodChannel#flutter.baseflow.com/geolocator/methods(25437): Failed to handle method call
E/MethodChannel#flutter.baseflow.com/geolocator/methods(25437): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.ContextWrapper.getApplicationContext()' on a null object reference
E/MethodChannel#flutter.baseflow.com/geolocator/methods(25437):   at com.baseflow.flutter.plugin.geolocator.tasks.LocationUsingLocationManagerTask.getLocationManager(LocationUsingLocationManagerTask.java:31)
E/MethodChannel#flutter.baseflow.com/geolocator/methods(25437):   at com.baseflow.flutter.plugin.geolocator.tasks.LastKnownLocationUsingLocationManagerTask.startTask(LastKnownLocationUsingLocationManagerTask.java:17)
E/MethodChannel#flutter.baseflow.com/geolocator/methods(25437):   at com.baseflow.flutter.plugin.geolocator.GeolocatorPlugin.onMethodCall(GeolocatorPlugin.java:54)
E/MethodChannel#flutter.baseflow.com/geolocator/methods(25437):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#flutter.baseflow.com/geolocator/methods(25437):   at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:165)
E/MethodChannel#flutter.baseflow.com/geolocator/methods(25437):   at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter.baseflow.com/geolocator/methods(25437):   at android.os.MessageQueue.next(MessageQueue.java:328)
E/MethodChannel#flutter.baseflow.com/geolocator/methods(25437):   at android.os.Looper.loop(Looper.java:148)
E/MethodChannel#flutter.baseflow.com/geolocator/methods(25437):   at android.app.ActivityThread.main(ActivityThread.java:6251)
E/MethodChannel#flutter.baseflow.com/geolocator/methods(25437):   at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter.baseflow.com/geolocator/methods(25437):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1075)
E/MethodChannel#flutter.baseflow.com/geolocator/methods(25437):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
``` 

### Expected behavior
No exception

### Reproduction steps
`flutter run` with above code snippet

### Configuration

**Version:** 1.6.2

**Platform:** 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.5.8, on Mac OS X 10.13.6 17G65, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.0)
[✓] Connected devices (1 available)

**Comment by sestegra** [comment]
I will try to update the code to use the Context directly available from registrar to avoid to pass by the Activity.

**Comment by mvanbeusekom** [comment]
@sestegra I checked our code and the error happens on the spot where the native code returns the result to Dart using the instance of the `MethodResult` class. Looking into the "android_alarm_manager", it looks like the `printHello` method is called from the background. Did you follow the instructions on the documentation of the "android_alarm_manager" explaining the usage of other Flutter plug-ins together with the "android_alarm_manager" (to following is copied directly from the [README](https://pub.dartlang.org/packages/android_alarm_manager)):

>If alarm callbacks will need access to other Flutter plugins, including the alarm manager plugin itself, it is necessary to teach the background service how to initialize plugins. This is done by giving the AlarmService a callback to call in the application's onCreate method. See the example's Application overrides. In particular, its Application class is as follows:
```dart
public class Application extends FlutterApplication implements PluginRegistrantCallback {
  @Override
  public void onCreate() {
    super.onCreate();
    AlarmService.setPluginRegistrant(this);
  }

  @Override
  public void registerWith(PluginRegistry registry) {
    GeneratedPluginRegistrant.registerWith(registry);
  }
}
```

**Comment by sestegra** [comment]
@mvanbeusekom I not only follow the documentation, I updated the example (that implements the Application class) to call Geolocator.

Basically, I cloned the plugins project, update the example code with above snippet and run it.

**Comment by sestegra** [comment]
I still got the following error coming from permissions.
```
D/permissions_handler( 9153): Unable to detect current Activity.
```

**Comment by sestegra** [comment]
It works if I get permission from MainActivity.

**Comment by mvanbeusekom** [comment]
@sestegra the problem with the permissions can also be solved by taking care of them manually when the App starts using the [permission_handler](https://pub.dartlang.org/packages/permission_handler) plugin. 

Unfortunately to take care of permissions we do need an `Activity` (which makes sense because we need to show the user a dialog). So by taking care of the permissions manually when we are sure the App is running (before we launch services in the background) we can be sure there is an activity.

Then when the `Geolocator` gets called it will notice that all permissions are taken care of and will simply continue acquiring the location and not try to get the required permissions.

**Comment by mvanbeusekom** [comment]
@sestegra a quick follow up, we just release version 1.6.3 of the Geolocator plug-in which includes your changes. Thanks again for reporting the issue.
