### ISSUE TITLE
placemarkFromCoordinates 'List' is not a subtype of type 'Future' error

### ISSUE THREAD

**Issue by fawadkhanucp** [BaseflowIT/flutter-geolocator#84]
## 🐛 Bug Report
When using placemarkFromCoordinates, I get the error type `'List<dynamic>' is not a subtype of type 'Future<dynamic>'` on line 192 in geolocator.dart.

Changing `    Future<dynamic> placemarks = await _methodChannel.invokeMethod(
        'placemarkFromCoordinates',
        <String, double>{"latitude": latitude, "longitude": longitude});` to

`    List<dynamic> placemarks = await _methodChannel.invokeMethod(
        'placemarkFromCoordinates',
        <String, double>{"latitude": latitude, "longitude": longitude});`

fixes the issue.

### Configuration
Flutter 0.7.0

**Version:** 1.6.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
@fawadkhanucp thank you for reporting this issue. I can indeed reproduce it (after upgrading my Flutter installation to 0.6.2 or higher).

I am currently working on it and will release a fix with version 1.6.3 later today.

**Comment by mvanbeusekom** [comment]
@fawadkhanucp  a quick follow up, we just release version 1.6.3 of the Geolocator plug-in which includes your changes. Thanks again for reporting the issue.

**Comment by fawadkhanucp** [comment]
@mvanbeusekom tested. working perfectly. thanks for the fast response. appreciate it.
