### ISSUE TITLE
Platform Exception locale = null

### ISSUE THREAD

**Issue by fawadkhanucp** [BaseflowIT/flutter-geolocator#92]
## 🐛 Bug Report

E/flutter (17224): PlatformException(error, locale == null, null)
E/flutter (17224): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551)
E/flutter (17224): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279)
E/flutter (17224): <asynchronous suspension>
E/flutter (17224): #2      Geolocator.placemarkFromCoordinates (package:geolocator/geolocator.dart:228)

### Expected behavior

It should be grabbing the locale from my phone if a locale isn't specified.

### Reproduction steps

Using placemarkFromCoordinates without passing a locale. Working perfectly if a locale is specified.

### Configuration

**Version:** 1.6.4
Flutter: 0.7.5

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
@fawadkhanucp thank you for reporting this bug, we will get to it immediately and send out an update today.

**Comment by mvanbeusekom** [comment]
@fawadkhanucp just a quick update, we just release version 1.6.5 which fixes the above issue.

Thanks again for reporting the issue.

**Comment by fawadkhanucp** [comment]
looks like the build failed

**Comment by mvanbeusekom** [comment]
@fawadkhanucp the code compiles correctly, we do however have some issues with Travis-CI timing out.

So we do need to go and see if we can optimize the build script to prevent these timeouts. For now I restarted the build job and hopefully all will go smooth now.

**Comment by fawadkhanucp** [comment]
ah okay. thanks

**Comment by fawadkhanucp** [comment]
does someone have to do something for it to get pushed to dart pub?

**Comment by mvanbeusekom** [comment]
@fawadkhanucp yes, and I was sure I did yesterday (guess not :-P)

**Comment by fawadkhanucp** [comment]
haha. thanks. appreciate all the quick responses.
