### ISSUE TITLE
Return number as placemark.name

### ISSUE THREAD

**Issue by aidooyaw1992** [BaseflowIT/flutter-geolocator#96]
i keep getting a number as name of my location when i use placemarkFromCoordinates

**Comment by mvanbeusekom** [comment]
Hi @aidooyaw1992, could you please provide a bit more information? To me it is not really clear what is going on and how to reproduce this and give you a good explanation on why this might be happening. It is entirely possible that a location name cannot be determined using the supplied coordinates.

The best would be if you fill in the [bug template](https://github.com/BaseflowIT/flutter-geolocator/issues/new?template=b-bug-report.md).

I would at least like to know the following information:

- Example coordinates (latitude, longitude)
- Version of the Plugin and Flutter 
- Which platforms (Android, iOS or both) you experience this issue

I will close this issue for now, you can re-open it with new information or simply add a new issue using the bug report I mentioned earlier.

**Comment by aidooyaw1992** [comment]
LatLng(5.6173468, -0.2342571)
Platform: Android
Flutter 1.0.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (6 weeks ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
